---
permalink: upgrade/upgrade-ontap-tools.html 
sidebar: sidebar 
keywords: upgrade 
summary: A atualização é compatível com implantações de HA e não HA. 
---
= Atualização das ONTAP tools for VMware vSphere 10.x para 10.5
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode atualizar as ONTAP tools for VMware vSphere 10.3 ou 10.4 para 10.5.  No entanto, para atualizar das ferramentas ONTAP 10.0, 10.1 ou 10.2 para 10.5, você deve primeiro atualizar para 10.3 ou 10.4 antes de prosseguir para 10.5.

[NOTE]
====
* Para sistemas ASA r2, certifique-se de atualizar para as ONTAP tools for VMware vSphere para 10.5 e ONTAP para 9.16.1, antes de configurar mais zonas de disponibilidade de armazenamento (SAZs).
* Se a atualização das ONTAP tools for VMware vSphere 10.3 ou 10.4 para 10.5 falhar, você não poderá reverter. Use RPO baixo ou recuperação de instantâneo para restaurar a configuração. Para ONTAP tools for VMware vSphere 10.2 e anteriores, use RPO zero para restaurar a configuração.


====
.Antes de começar
* Certifique-se de que todos os nós estejam ativos.
* Certifique-se de que o certificado do sistema ONTAP e os certificados vCenter integrados sejam válidos por pelo menos 5 dias. Se os certificados expirarem antes, a atualização falhará.
* Certifique-se de ter um quinto disco com capacidade de 100 GB em todos os nós.
* Verifique se a configuração do nó corresponde às especificações na tabela abaixo.


|===
| Tipo de implantação | CPU (núcleo) por nó | Memória (GB) por nó | Espaço em disco (GB) por nó | CPU total (núcleo) | Memória (GB) | Espaço total em disco (GB) 


| Não-HA pequeno | 9 | 18 | 350 | 9 | 18 | 350 


| Meio não-HA | 13 | 26 | 350 | 13 | 26 | 350 


| HA pequena | 9 | 18 | 350 | 27 | 54 | 1050 


| HA média | 13 | 26 | 350 | 39 | 78 | 1050 


| HA grande | 17 | 34 | 350 | 51 | 102 | 1050 
|===
* Certifique-se de que o hot plug-in para CPU e RAM esteja habilitado.
* Habilite o backup com RPO baixo e certifique-se de que um dos backups esteja visível na interface do vCenter Client.  Faça o download da pasta de backup antes de atualizar.
* Recomenda-se backup com RPO baixo.  No entanto, em implantações sem alta disponibilidade (HA), você pode tirar um snapshot quiescente da máquina virtual das ferramentas ONTAP antes de atualizar.
+
Consulte link:../manage/backup-settings.html["Editar configurações de backup"] e link:../manage/recover-backup.html["Recuperar a configuração das ferramentas ONTAP"] Para obter mais informações sobre backup e recuperação.



.Passos
. Faça o upload das ferramentas do ONTAP para a ISO de atualização do VMware vSphere para a biblioteca de conteúdo.
. Na página principal da VM, selecione *Ações* > *Editar configurações*. Para identificar o nome da máquina virtual principal:
+
.. Ative o shell de diagnóstico em qualquer nó.
.. Execute o seguinte comando:
`grep sourceHost /opt/netapp/meta/ansible_vars.yaml`


. Selecione o *arquivo ISO da biblioteca de conteúdo* na janela de edição de configurações, no campo *unidade de CD/DVD*.
. Selecione o arquivo ISO, marque a caixa *Conectado* para o campo *unidade de CD/DVD* e clique em *OK*.
. No vCenter Server, abra um console para as ferramentas do ONTAP.
. Inicie sessão como utilizador de manutenção.
. Digite *2* para selecionar o menu *Configuração do Sistema*.
. Digite *7* para selecionar a opção *Atualizar*.
. Forneça as credenciais do vCenter quando solicitado.  Esta é a instância do vCenter onde as ferramentas ONTAP estão hospedadas.
+
Se você estiver usando as ferramentas ONTAP em uma topologia de dois servidores vCenter — onde o dispositivo está hospedado em uma instância do vCenter e gerencia outra — você pode atribuir uma função restrita à instância do vCenter que hospeda as ferramentas ONTAP .  Você pode criar um usuário e uma função dedicados do vCenter com apenas as permissões de armazenamento de dados listadas abaixo:

+
** Alocar espaço
** Navegar pelo armazenamento de dados
** Operações de arquivo de baixo nível
** Remover arquivo
** Atualizar arquivos da máquina virtual
** Atualizar metadados da máquina virtual
+
Para a instância do vCenter que será gerenciada pelas ferramentas ONTAP , certifique-se de que a conta de usuário do vCenter tenha privilégios de administrador.

+
Durante a atualização, se algum certificado de backend de armazenamento integrado não tiver entradas de Nome Alternativo de Assunto (SAN), você receberá um prompt indicando o SAN ausente.  Se você optar por prosseguir sem validar o SAN, a atualização continuará, mas isso não é recomendado devido a potenciais riscos de segurança.



. Ao atualizar, as seguintes ações são executadas automaticamente:
+
.. O certificado de gateway é renovado com um período de validade de 1 ano.  Quando você remove o adaptador SRA anterior e carrega o novo adaptador 10.5, a validade do certificado SRA muda de 10 anos para 1 ano.
.. O plug-in remoto foi atualizado
.. Os certificados ONTAP e vCenter Server são validados e adicionados às ferramentas ONTAP
.. O backup está habilitado




.O que vem a seguir
Após a atualização para as ONTAP tools for VMware vSphere 10.5:

* Monitore os alertas do sistema e planeje renovar o certificado do gateway antes que ele expire em um ano.
* Remova o adaptador SRA das ferramentas ONTAP 10.4 ou 10.3 e carregue o arquivo tar do adaptador SRA 10.5.
* Execute o comando de instalação após carregar o arquivo tar do adaptador SRA. Em seguida, verifique novamente os adaptadores SRA para atualizar a página de adaptadores de replicação de armazenamento do VMware Site Recovery.


Após a atualização, você pode:

* Desative os serviços da interface de usuário do gerenciador
* Passar de uma configuração que não seja HA para uma configuração HA
* Amplie uma configuração pequena não HA para uma configuração média não HA ou para uma configuração média ou grande HA.


.Informações relacionadas
link:../migrate/migrate-to-latest-ontaptools.html["Migrar das ONTAP tools for VMware vSphere 9.xx para 10.5"]
