---
permalink: migrate/sra-vasa-migration.html 
sidebar: sidebar 
keywords: migrate 
summary: Ao migrar dados de storage, os back-ends de storage são integrados manualmente usando APIS REST. Ao migrar dados do provedor VASA, os dados são exportados do banco de dados Derby existente e importados para o banco de dados MongoDB. 
---
= Migrar o Provedor VASA e atualizar o SRA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/




== Etapas para migrar o provedor VASA

. Para ativar A PORTA Derby 1527 nas ferramentas existentes do ONTAP para VMware vSphere, ative o usuário raiz e faça login na CLI por meio de SSH. Em seguida, execute o seguinte comando:
+
[listing]
----
iptables -I INPUT 1 -p tcp --dport 1527 -j ACCEPT
----
. Implante o OVA para ONTAP tools for VMware vSphere 10.5.
. Adicione a instância do vCenter Server que você deseja migrar para as ONTAP tools for VMware vSphere 10.5. Consulte link:../configure/add-vcenter.html["Adicione uma instância do vCenter Server"] para maiores informações.
. Integre o backend de armazenamento localmente a partir das APIs do servidor vCenter para o plug-in de ferramentas ONTAP.
. Emita a seguinte API do Swagger ou no Postman para migrar.
+
curl -X POST  `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/{vcguid}/migration-jobs`

+
Você pode acessar o Swagger através deste URL: `\https://$FQDN_IP_PORT/` , por exemplo: `\https://10.67.25.33:8443/` .

+
[]
====
*Método HTTP e endpoint*

Essa chamada de API REST usa o método e o endpoint a seguir.

|===


| *Método HTTP* | *Caminho* 


| POST | /api/v1 
|===
*Tipo de processamento*

Assíncrono

*Curl exemplo*

curl -X POST 'https://<OTV-NG-IP>:8443/virtualization/api/v1/vcenters/<vcguid>/migration-jobs'[] \ --header 'x-auth: <token_de_autenticação>' \ --header 'Tipo de conteúdo: aplicativo/json' \ --data '{ "otv_ip": "xx.xx.xx.xx", "vasa_provider_credentials": { "nome de usuário": "xxxxx", "senha": "******" }, "senha_do_banco_de_dados": "******" }'

Corpo de solicitação para outra migração de liberação:

{ "otv_ip": "xx.xx.xx.xx", "vasa_provider_credentials": { "nome de usuário": "xxxxx", "senha": "*******" } }

* Exemplo de saída JSON*

Um objeto de tarefa é retornado. Você deve salvar o identificador do trabalho para usá-lo na próxima etapa.

[id]: 123, "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35", "status": "running"

====
. Use o seguinte URI no Swagger para verificar o status:
+
[listing]
----
curl `\https://xx.xx.xx.xxx:8443/virtualization/api/jobmanager/v2/jobs/<JobID>?includeSubJobsAndTasks=true`
----
+
Depois de concluir o trabalho, reveja o relatório de migração. Este relatório está incluído nos dados do trabalho e pode ser acedido a partir da resposta do trabalho.

. Adicione as ferramentas ONTAP para o provedor de armazenamento VMware vSphere ao vCenter Server e link:../configure/registration-process.html["Registe o Fornecedor VASA"] com ferramentas ONTAP para VMware vSphere.
. link:../manage/enable-services.html["Ative o fornecedor VASA"]serviço em ONTAP tools for VMware vSphere 10.5.
. Pare as ferramentas do ONTAP para o provedor de armazenamento VMware vSphere 9,10/9,11/9,12/9,13 Serviço do provedor VASA a partir do console de manutenção.
+
não exclua o VASA Provider.

+
Após a interrupção do antigo Provedor VASA, o vCenter Server faz failover para as ONTAP tools for VMware vSphere. Todos os datastores e VMs se tornam acessíveis e são atendidos pelas ONTAP tools for VMware vSphere.

. Os datastores NFS e VMFS migrados das ONTAP tools for VMware vSphere 9.xxx ficam visíveis nas ONTAP tools for VMware vSphere 10.5 somente depois que o trabalho de descoberta do datastore é acionado, o que pode levar até 30 minutos para ser concluído.  Verifique se os armazenamentos de dados estão visíveis na página de visão geral das ferramentas ONTAP para a página de interface do usuário do plug-in VMware vSphere.
. Execute a migração de patch usando a seguinte API no Swagger ou no Postman:
+
[]
====
*Método HTTP e endpoint*

Essa chamada de API REST usa o método e o endpoint a seguir.

|===


| *Método HTTP* | *Caminho* 


| PATCH | /api/v1 
|===
*Tipo de processamento*

Assíncrono

*Curl exemplo*

curl -X PATCH  `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/56d373bd-4163-44f9-a872-9adabb008ca9/migration-jobs/84dr73bd-9173-65r7-w345-8ufdbb887d43`

* Exemplo de saída JSON*

Um objeto de tarefa é retornado. Você deve salvar o identificador do trabalho para usá-lo na próxima etapa.

[id]: 123, "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35", "status": "running"

O corpo da solicitação está vazio para operação de patch.


NOTE: UUID é a migração UUID retornada em resposta à API pós-migração.

Depois de executar a API de migração de patches, todas as VMs estão em conformidade com a política de storage.

====


.O que vem a seguir
Após concluir a migração e registrar o ONTAP Tools 10.5 no vCenter Server, siga estas etapas:

* Aguarde que *Discovery* seja concluído, os certificados serão atualizados automaticamente em todos os hosts.
* Aguarde tempo suficiente antes de iniciar as operações do armazenamento de dados e da máquina virtual. O período de espera necessário varia de acordo com o número de hosts, armazenamentos de dados e máquinas virtuais na configuração. A não espera pode resultar em falhas operacionais intermitentes.


Após a atualização, se o estado de conformidade da máquina virtual estiver desatualizado, reaplique a política de armazenamento usando as seguintes etapas:

. Acesse o armazenamento de dados e selecione *Resumo* > *Políticas de armazenamento de VM*.
+
O status de conformidade em *conformidade com a política de armazenamento de VM* é exibido como *desatualizado*.

. Selecione a política Storage VM e a VM correspondente
. Selecione *aplicar*
+
O status de conformidade em *conformidade com a política de armazenamento de VM* agora é mostrado como compatível.



.Informações relacionadas
* link:../concepts/rbac-learn-about.html["Saiba mais sobre as ferramentas do ONTAP para VMware vSphere 10 RBAC"]
* link:../upgrade/upgrade-ontap-tools.html["Atualização das ONTAP tools for VMware vSphere 10.x para 10.5"]




== Etapas para atualizar o adaptador de replicação de armazenamento (SRA)

.Antes de começar
No plano de recuperação, o site protegido refere-se ao local onde as VMs estão em execução, enquanto o site de recuperação é onde as VMs serão recuperadas. A interface do dispositivo VMware Live Site Recovery exibe o estado do plano de recuperação com detalhes sobre os sites protegidos e de recuperação.  No plano de recuperação, os botões LIMPAR e REPROTEGER são desabilitados, enquanto os botões TESTE e EXECUTAR permanecem habilitados. Isso indica que o site está preparado para recuperação de dados. Antes de migrar o SRA, verifique se um site está no estado protegido e o outro no estado de recuperação.


NOTE: Não inicie a migração se o failover tiver sido concluído, mas a nova proteção estiver pendente.  Certifique-se de que o processo de reproteção seja concluído antes de prosseguir com a migração.  Se um failover de teste estiver em andamento, limpe-o e inicie a migração.

. Siga estas etapas para excluir o adaptador SRA das ferramentas do ONTAP para VMware vSphere 9.xx na recuperação de site da VMware:
+
.. Vá para a página de gerenciamento de configuração do VMware Live Site Recovery
.. Vá para a seção *Storage Replication Adapter*.
.. No menu de elipses, selecione *Reset Configuration*.
.. No menu de elipses, selecione *Delete*.


. Execute estas etapas nos locais de proteção e recuperação.
+
.. link:../manage/enable-services.html["Habilite as ferramentas do ONTAP para os serviços do VMware vSphere"]
.. Configure as ONTAP tools for VMware vSphere 10.5 SRA usando as etapas emlink:../protect/configure-on-srm-appliance.html["Configure o SRA no VMware Live Site Recovery Appliance"] .
.. Na página de interface de usuário do VMware Live Site Recovery, execute as operações *Discover Arrays* e *Discover Devices* e confirme se os dispositivos são exibidos como antes da migração.



