---
permalink: migrate/sra-vasa-migration.html 
sidebar: sidebar 
keywords: migrate 
summary: Ao migrar dados de storage, os back-ends de storage são integrados manualmente usando APIS REST. Ao migrar dados do provedor VASA, os dados são exportados do banco de dados Derby existente e importados para o banco de dados MongoDB. 
---
= Migre o provedor VASA e atualize o SRA nas ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga os passos desta seção para migrar o provedor VASA das ONTAP tools for VMware vSphere 9.xx para as ONTAP tools for VMware vSphere 10.5 e atualizar o Adaptador de Replicação de Armazenamento (SRA) no dispositivo VMware Live Site Recovery.



== Etapas para migrar o provedor VASA

. Para ativar A PORTA Derby 1527 nas ferramentas existentes do ONTAP para VMware vSphere, ative o usuário raiz e faça login na CLI por meio de SSH. Em seguida, execute o seguinte comando:
+
[listing]
----
iptables -I INPUT 1 -p tcp --dport 1527 -j ACCEPT
----
. Implante o OVA para ONTAP tools for VMware vSphere 10.5.
. Adicione a instância do vCenter Server que você deseja migrar para as ONTAP tools for VMware vSphere 10.5. Consulte link:../configure/add-vcenter.html["Adicione uma instância do vCenter Server"] para maiores informações.
. link:../manage/enable-services.html["Ative o fornecedor VASA"]serviço em ONTAP tools for VMware vSphere 10.5.
. Integre o backend de armazenamento localmente a partir das APIs do servidor vCenter para o plug-in de ferramentas ONTAP . Consultelink:../configure/add-storage-backend.html["Adicione um backend de armazenamento usando a interface do cliente vSphere."] Para obter mais informações.
. Obtenha um token de acesso para autenticar solicitações à API REST.  Utilize o exemplo a seguir, substituindo as variáveis por valores específicos do seu ambiente.
+
[source, curl]
----
curl --request POST \
  --location "https://$FQDN_IP_PORT/virtualization/api/v1/auth/vcenter-login" \
  --header "Content-Type: application/json" \
  --header "Accept: */*" \
  -d '{"username": "$MYUSER", "password": "$MYPASSWORD", "vcenter hostname": "$MYVCENTER"}'
----
+
Copie e salve o token de acesso retornado na resposta.

. Emita a seguinte API a partir do Swagger ou Postman para migrar.
+
[listing]
----
curl -X POST `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/{vcguid}/migration-jobs`
----
+
Você pode acessar o Swagger através deste URL: `\https://$FQDN_IP_PORT/` , por exemplo: `\https://10.67.25.33:8443/` .

+
[]
====
*Método HTTP e endpoint*

Essa chamada de API REST usa o método e o endpoint a seguir.

|===


| *Método HTTP* | *Caminho* 


| POST | /api/v1 
|===
*Tipo de processamento*

Assíncrono

*Curl exemplo*

[listing]
----
curl -X POST 'https://<OTV-NG-IP>:8443/virtualization/api/v1/vcenters/<vcguid>/migration-jobs' \
  --header 'x-auth: <auth_token>' \
  --header 'Content-Type: application/json' \
  --data '{
    "otv_ip": "xx.xx.xx.xx",
    "vasa_provider_credentials": {
      "username": "xxxxx",
      "password": "******"
    },
    "database_password": "******"
  }'
----
Corpo de solicitação para outra migração de liberação:

[listing]
----
{
  "otv_ip": "xx.xx.xx.xx",
  "vasa_provider_credentials": {
    "username": "xxxxx",
    "password": "*******"
  }
}
----
* Exemplo de saída JSON*

O sistema retorna um objeto de trabalho.  Salve o identificador do trabalho para usá-lo na próxima etapa.

[listing]
----
{
  "id": 123,
  "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35",
  "status": "running"
}
----
====
. Use o seguinte URI no Swagger para verificar o status:
+
[listing]
----
curl `\https://xx.xx.xx.xxx:8443/virtualization/api/jobmanager/v2/jobs/<JobId>?includeSubJobsAndTasks=true`
----
+
Utilize o valor 'id' retornado pela tarefa de migração na etapa anterior. Após a conclusão da tarefa, revise o relatório de migração na resposta da tarefa.

. Registre o provedor VASA com as ONTAP tools for VMware vSphere. Para obter instruções, consultelink:../configure/registration-process.html["Registe o Fornecedor VASA"] .
. Verifique o registro do VASA Provider:
+
.. No vSphere Client, navegue até o vCenter Server.
.. Selecione *Configurar* > *Provedores de armazenamento*.
.. Confirme que o VASA Provider registrado na etapa anterior aparece online.


. Pare as ONTAP tools for VMware vSphere 9.10/9.11/9.12/9.13 VASA seguindo estes passos:
+
.. Nas ferramentas ONTAP 9.x, abra o console da web.
.. Acesse o console de manutenção.
.. Digitar `1` Para selecionar o menu *Configuração do Aplicativo*.
.. Digitar `5` interromper os serviços do provedor VASA e do SRA.
.. No vSphere Client, navegue até o vCenter Server e selecione *Configurar* > *Provedores de armazenamento*.
.. Selecione o VASA Provider offline para ONTAP tools 9.x e selecione *Remover*.
+
Após a interrupção do antigo Provedor VASA, o vCenter Server faz failover para as ONTAP tools for VMware vSphere. Todos os datastores e VMs se tornam acessíveis e são atendidos pelas ONTAP tools for VMware vSphere.



. Os datastores NFS e VMFS migrados aparecem nas ONTAP tools for VMware vSphere 10.5 após o trabalho de descoberta do datastore, que pode levar até 30 minutos.  Verifique a visibilidade deles na página de visão geral.
. Execute a migração de patch usando a seguinte API no Swagger ou no Postman:
+
[]
====
*Método HTTP e endpoint*

Essa chamada de API REST usa o método e o endpoint a seguir.

|===


| *Método HTTP* | *Caminho* 


| PATCH | /api/v1 
|===
*Tipo de processamento*

Assíncrono

Utilize o seguinte URI no Swagger:

[listing]
----
curl  -X PATCH  `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/<vcenter_id>/migration-jobs/<migration_id>`
----
*Método HTTP e endpoint*

Essa chamada de API REST usa o método e o endpoint a seguir.

|===


| *Método HTTP* | *Caminho* 


| PATCH | /api/v1 
|===
*Tipo de processamento*

Assíncrono

Utilize o seguinte URI no Swagger:

[listing]
----
curl  -X PATCH  `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/<vcenter_id>/migration-jobs/<migration_id>`
----
*Curl exemplo*

[listing]
----
curl  -X PATCH  `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/56d373bd-4163-44f9-a872-9adabb008ca9/migration-jobs/d50073ce-35b4-4c51-9d2e-4ce66f802c35`
----
* Exemplo de saída JSON*

[listing]
----
{
  "id": 123,
  "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35",
  "status": "running"
}
----
====
+

NOTE: Utilize o valor 'migration_id' retornado na Etapa 7 como <migration_id> na chamada da API PATCH. O corpo da requisição está vazio para a operação de patch.

+

NOTE: UUID é a migração UUID retornada em resposta à API pós-migração.



Depois de executar a API de migração de patches, todas as VMs estão em conformidade com a política de storage.

.O que vem a seguir
Após concluir a migração e registrar o ONTAP Tools 10.5 no vCenter Server, siga estas etapas:

* Aguarde a conclusão da *Descoberta* e o sistema atualizará os certificados automaticamente em todos os hosts.
* Aguarde antes de iniciar as operações do armazenamento de dados e da máquina virtual.  O tempo de espera depende do número de hosts, armazenamentos de dados e máquinas virtuais.  Se você não esperar, poderá ver falhas ocasionais.


Após a atualização, se o estado de conformidade da máquina virtual estiver desatualizado, reaplique a política de armazenamento usando as seguintes etapas:

. Acesse o armazenamento de dados e selecione *Resumo* > *Políticas de armazenamento de VM*.
. O sistema mostra o status de conformidade em *Conformidade da política de armazenamento de VM* como *Desatualizado*.
. Selecione a política de VM de armazenamento e a VM correspondente.
. Selecione *Aplicar*.
. O status de conformidade em *Conformidade da política de armazenamento de VM* é exibido como compatível.


.Informações relacionadas
* link:../concepts/rbac-learn-about.html["Saiba mais sobre as ferramentas do ONTAP para VMware vSphere 10 RBAC"]
* link:../upgrade/upgrade-ontap-tools.html["Atualização das ONTAP tools for VMware vSphere 10.x para 10.5"]




== Etapas para atualizar o adaptador de replicação de armazenamento (SRA)

.Antes de começar
No plano de recuperação, o site protegido refere-se ao local onde as VMs estão em execução, enquanto o site de recuperação é onde as VMs serão recuperadas. A interface do dispositivo VMware Live Site Recovery exibe o estado do plano de recuperação com detalhes sobre os sites protegidos e de recuperação.  No plano de recuperação, os botões LIMPAR e REPROTEGER são desabilitados, enquanto os botões TESTE e EXECUTAR permanecem habilitados. Isso indica que o site está preparado para recuperação de dados. Antes de migrar o SRA, verifique se um site está no estado protegido e o outro no estado de recuperação.


NOTE: Não inicie a migração se o failover tiver sido concluído, mas a reproteção estiver pendente. Certifique-se de que o processo de reproteção seja concluído antes de prosseguir com a migração. Se um failover de teste estiver em andamento, finalize o failover de teste e inicie a migração.

. Siga estas etapas para excluir o adaptador SRA das ferramentas do ONTAP para VMware vSphere 9.xx na recuperação de site da VMware:
. Acesse a página de gerenciamento de configuração do VMware Live Site Recovery.
+
.. Vá para a seção *Storage Replication Adapter*.
.. No menu de elipses, selecione *Reset Configuration*.
.. No menu de elipses, selecione *Delete*.


. Execute estas etapas nos locais de proteção e recuperação.
+
.. link:../manage/enable-services.html["Habilite as ferramentas do ONTAP para os serviços do VMware vSphere"]
.. Configure as ONTAP tools for VMware vSphere 10.5 SRA usando as etapas emlink:../protect/configure-on-srm-appliance.html["Configure o SRA no VMware Live Site Recovery Appliance"] .
.. Na interface do VMware Live Site Recovery, execute *Discover Arrays* e *Discover Devices*.  Confirme se os dispositivos são exibidos como antes da migração.



