---
permalink: migrate/sra-vasa-migration.html 
sidebar: sidebar 
keywords: VASA Provider migration, SRA update, VMware Live Site Recovery, ONTAP tools migration, vVols migration, migration jobs, Swagger, REST API 
summary: Migre o provedor VASA e atualize o SRA das ONTAP tools 9.x para 10.6 para o VMware Live Site Recovery. 
---
= Migre o provedor VASA e atualize o SRA nas ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Use esta tarefa para migrar o VASA Provider das ONTAP tools for VMware vSphere 9.xx para 10.6 e atualizar o Storage Replication Adapter (SRA) no appliance VMware Live Site Recovery.



[[migrate-the-vasa-provider]]
== Migrar o provedor VASA

.Antes de começar
Certifique-se de que ONTAP tools for VMware vSphere 10.6 esteja implantado e que o vCenter Server de destino e os backends de storage estejam prontos para a migração.

. Para habilitar a porta 1527 do Derby no appliance ONTAP tools for VMware vSphere existente, habilite o usuário raiz, faça login na CLI via SSH e execute o seguinte comando:
+
[listing]
----
iptables -I INPUT 1 -p tcp --dport 1527 -j ACCEPT
----
. Implante o OVA para ONTAP tools for VMware vSphere 10.6.
. Adicione a instância do servidor vCenter que você deseja migrar para ONTAP tools for VMware vSphere 10.6. Consulte link:../configure/add-vcenter.html["Adicione uma instância do vCenter Server"] para mais informações.
. Integre o backend de armazenamento localmente por meio das APIs do servidor vCenter para o plug-in ONTAP tools. Consulte link:../configure/add-storage-backend.html["Adicione um backend de armazenamento usando a interface do vSphere Client"] para obter mais informações.
. Obtenha um token de acesso para autenticar solicitações à API REST.  Utilize o exemplo a seguir, substituindo as variáveis por valores específicos do seu ambiente.
+
[source, curl]
----
curl --request POST \
  --location "https://$FQDN_IP_PORT/virtualization/api/v1/auth/vcenter-login" \
  --header "Content-Type: application/json" \
  --header "Accept: */*" \
  -d '{"username": "$MYUSER", "password": "$MYPASSWORD", "vcenter hostname": "$MYVCENTER"}'
----
+
Copie e salve o token de acesso retornado na resposta.

. Faça a seguinte chamada de API de migração a partir do Swagger ou do Postman.
+
[listing]
----
curl -X POST `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/{vcguid}/migration-jobs`
----
+
Você pode acessar o Swagger através deste URL: `\https://$FQDN_IP_PORT/` , por exemplo: `\https://10.67.25.33:8443/` .

+
[]
====
*Método HTTP e endpoint*

Essa chamada de API REST usa o método e o endpoint a seguir.

|===


| *Método HTTP* | *Caminho* 


| POST | /api/v1 
|===
*Tipo de processamento*

Assíncrono

*Curl exemplo*

[listing]
----
curl -X POST 'https://<OTV-NG-IP>:8443/virtualization/api/v1/vcenters/<vcguid>/migration-jobs' \
  --header 'x-auth: <auth_token>' \
  --header 'Content-Type: application/json' \
  --data '{
    "otv_ip": "xx.xx.xx.xx",
    "vasa_provider_credentials": {
      "username": "xxxxx",
      "password": "******"
    },
    "database_password": "******"
  }'
----
Corpo de solicitação para outra migração de liberação:

[listing]
----
{
  "otv_ip": "xx.xx.xx.xx",
  "vasa_provider_credentials": {
    "username": "xxxxx",
    "password": "*******"
  }
}
----
* Exemplo de saída JSON*

O sistema retorna um objeto de trabalho.  Salve o identificador do trabalho para usá-lo na próxima etapa.

[listing]
----
{
  "id": 123,
  "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35",
  "status": "running"
}
----
====




[[check-migration-status]]
=== Verifique o status da migração

. Use o seguinte URI no Swagger para verificar o status:
+
[listing]
----
curl `\https://xx.xx.xx.xxx:8443/virtualization/api/jobmanager/v2/jobs/<JobId>?includeSubJobsAndTasks=true`
----
+
Utilize o valor 'id' retornado pela tarefa de migração na etapa anterior. Após a conclusão da tarefa, revise o relatório de migração na resposta da tarefa.





[[register-and-verify-the-migrated-vasa-provider]]
=== Registre e verifique o provedor VASA migrado

. Registre o provedor VASA com as ONTAP tools for VMware vSphere. Para obter instruções, consultelink:../configure/registration-process.html["Registe o Fornecedor VASA"] .
. Verifique o registro do VASA Provider:
+
.. No vSphere Client, navegue até o vCenter Server.
.. Selecione *Configurar* > *Provedores de armazenamento*.
.. Confirme que o VASA Provider registrado na etapa anterior aparece online.


. Pare as ONTAP tools for VMware vSphere 9.10/9.11/9.12/9.13 VASA seguindo estes passos:
+
.. Nas ferramentas ONTAP 9.x, abra o console da web.
.. Faça login usando as `maint` credenciais.
.. Digitar `1` Para selecionar o menu *Configuração do Aplicativo*.
.. Digitar `5` interromper os serviços do provedor VASA e do SRA.
.. No vSphere Client, navegue até o vCenter Server e selecione *Configurar* > *Provedores de armazenamento*.
.. Selecione o VASA Provider offline para ONTAP tools 9.x e selecione *Remover*.
+
Após a interrupção do provedor VASA antigo, o vCenter Server realiza o failover para ONTAP tools for VMware vSphere. Todos os datastores e VMs tornam-se acessíveis e são servidos a partir do ONTAP tools for VMware vSphere.



. Os datastores NFS e VMFS migrados aparecem em ONTAP tools for VMware vSphere 10.6 após a tarefa de descoberta do datastore, que pode levar até 30 minutos. Verifique a visibilidade deles na página de visão geral.




[[run-the-patch-migration]]
=== Execute a migração de patches

. Execute a chamada da API de migração de patches usando Swagger ou Postman:
+
[]
====
*Método HTTP e endpoint*

Essa chamada de API REST usa o método e o endpoint a seguir.

|===


| *Método HTTP* | *Caminho* 


| PATCH | /api/v1 
|===
*Tipo de processamento*

Assíncrono

Utilize o seguinte URI no Swagger:

[listing]
----
curl  -X PATCH  `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/<vcenter_id>/migration-jobs/<migration_id>`
----
*Método HTTP e endpoint*

Essa chamada de API REST usa o método e o endpoint a seguir.

|===


| *Método HTTP* | *Caminho* 


| PATCH | /api/v1 
|===
*Tipo de processamento*

Assíncrono

Utilize o seguinte URI no Swagger:

[listing]
----
curl  -X PATCH  `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/<vcenter_id>/migration-jobs/<migration_id>`
----
*Curl exemplo*

[listing]
----
curl  -X PATCH  `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/56d373bd-4163-44f9-a872-9adabb008ca9/migration-jobs/d50073ce-35b4-4c51-9d2e-4ce66f802c35`
----
* Exemplo de saída JSON*

[listing]
----
{
  "id": 123,
  "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35",
  "status": "running"
}
----
====
+

NOTE: Utilize o valor 'migration_id' retornado na Etapa 7 como <migration_id> na chamada da API PATCH. O corpo da requisição está vazio para a operação de patch.

+

NOTE: UUID é a migração UUID retornada em resposta à API pós-migração.



Depois de executar a API de migração de patches, todas as VMs estão em conformidade com a política de storage.



[[after-migration]]
== Após a migração

Após concluir a migração e registrar ONTAP tools 10.6 no vCenter Server, siga estas etapas:

* Aguarde a conclusão da *Descoberta* e o sistema atualizará os certificados automaticamente em todos os hosts.
* Aguarde antes de iniciar as operações do armazenamento de dados e da máquina virtual.  O tempo de espera depende do número de hosts, armazenamentos de dados e máquinas virtuais.  Se você não esperar, poderá ver falhas ocasionais.


Após a atualização, se o estado de conformidade da máquina virtual estiver desatualizado, reaplique a política de armazenamento usando as seguintes etapas:

. Acesse o armazenamento de dados e selecione *Resumo* > *Políticas de armazenamento de VM*.
. O sistema mostra o status de conformidade em *Conformidade da política de armazenamento de VM* como *Desatualizado*.
. Selecione a política de VM de armazenamento e a VM correspondente.
. Selecione *Aplicar*.
. O status de conformidade em *Conformidade da política de armazenamento de VM* é exibido como compatível.


.Informações relacionadas
* link:../concepts/rbac-learn-about.html["Saiba mais sobre as ferramentas do ONTAP para VMware vSphere 10 RBAC"]
* link:../upgrade/upgrade-ontap-tools.html["Atualize das ONTAP tools for VMware vSphere 10.x para 10.6"]




[[update-the-storage-replication-adapter-sra]]
== Atualize o adaptador de replicação de storage (SRA)

.Antes de começar
Antes de migrar o SRA, verifique o seguinte:

* No plano de recuperação, o site protegido é o local onde as VMs estão atualmente em execução e o site de recuperação é o local onde as VMs serão recuperadas.
* Na interface do appliance VMware Live Site Recovery, um site aparece no estado protegido e o outro site aparece no estado de recuperação.
* No plano de recuperação, os botões *LIMPAR* e *REPROTEGER* estão desativados, e os botões *TESTAR* e *EXECUTAR* permanecem ativados.



NOTE: Não inicie a migração se o failover tiver sido concluído, mas a reproteção estiver pendente. Certifique-se de que o processo de reproteção seja concluído antes de prosseguir com a migração. Se um failover de teste estiver em andamento, finalize o failover de teste e inicie a migração.

. Siga estas etapas para excluir o adaptador SRA das ferramentas do ONTAP para VMware vSphere 9.xx na recuperação de site da VMware:
. Acesse a página de gerenciamento de configuração do VMware Live Site Recovery.
+
.. Vá para a seção *Storage Replication Adapter*.
.. No menu de elipses, selecione *Reset Configuration*.
.. No menu de elipses, selecione *Delete*.


. Execute estas etapas nos locais de proteção e recuperação.
+
.. link:../manage/enable-services.html["Habilite as ferramentas do ONTAP para os serviços do VMware vSphere"]
.. Configure as ONTAP tools for VMware vSphere 10.6 SRA usando as etapas em link:../protect/configure-on-srm-appliance.html["Configure o SRA no VMware Live Site Recovery Appliance"].
.. Na interface do VMware Live Site Recovery, execute *Discover Arrays* e *Discover Devices*.  Confirme se os dispositivos são exibidos como antes da migração.



