---
permalink: deploy/ontap-tools-deployment.html 
sidebar: sidebar 
keywords:  
summary: As ferramentas do ONTAP para o dispositivo VMware vSphere sempre são implantadas como nó único de pequeno porte com serviços principais para dar suporte a armazenamentos de dados NFS/VMFS. 
---
= Implantar as ferramentas do ONTAP para o VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
As ferramentas do ONTAP para o dispositivo VMware vSphere sempre são implantadas como nó único de pequeno porte com serviços principais para dar suporte a armazenamentos de dados NFS/VMFS.

*Antes de começar*

Uma biblioteca de conteúdo no VMware é um objeto de contentor que armazena modelos de VM, modelos vApp e outros tipos de arquivos. A implantação com biblioteca de conteúdo oferece uma experiência perfeita, pois não depende da conetividade de rede.


NOTE: Você deve armazenar a biblioteca de conteúdo em um datastore compartilhado, de modo que todos os hosts em um cluster possam acessá-la. Você precisa criar uma biblioteca de conteúdo para armazenar o OVA antes de alterar as configurações do dispositivo para a configuração HA. O modelo de biblioteca de conteúdo, uma vez carregado, não deve ser excluído após a implantação.


NOTE: Para ativar a implantação de HA mais tarde, a máquina virtual que hospeda as ferramentas do ONTAP não deve ser implantada diretamente em um host ESXi. Em vez disso, ele deve ser implantado em um cluster ou em um pool de recursos.

Se você ainda não tiver uma biblioteca de conteúdo adequada, crie uma usando as seguintes etapas:


NOTE: Se você pretende usar apenas uma implantação de nó único pequeno, não é necessário criar uma biblioteca de conteúdo.

. Faça o download do `.zip` arquivo que contém binários (_.ova_) e certificados assinados para ferramentas do ONTAP para VMware vSphere no https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["Site de suporte da NetApp"^] .
. Faça login no cliente vSphere usando `\https://vcenterip/ui`
. Selecione as elipses horizontais ao lado do cliente vSphere e selecione *Content Library*.
. Selecione *criar* à direita da página.
. Forneça um nome para a biblioteca e crie a biblioteca de conteúdo.
. Navegue até a biblioteca de conteúdo que você criou.
. Selecione *ações* à direita da página e selecione *Importar item* e importe o arquivo OVA.



NOTE: Para obter mais informações, https://blogs.vmware.com/vsphere/2020/01/creating-and-using-content-library.html["Criando e usando a Biblioteca de conteúdo"] consulte o blog.

Certifique-se de que importou o OVA para a sua biblioteca de conteúdo.


NOTE: Antes de prosseguir com a implantação, defina o DRS (Distributed Resource Scheduler) do cluster no inventário como 'Conservador' durante a instalação de ferramentas do ONTAP. Isso garante que as VMs não migrem durante a instalação.

*Passos*

. Faça o download do `.zip` arquivo que contém binários (_.ova_) e certificados assinados para ferramentas do ONTAP para VMware vSphere no https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["Site de suporte da NetApp"^] . Se você tiver importado o OVA para a biblioteca de conteúdo, você pode pular esta etapa e prosseguir com a próxima etapa, pois pode implantar diretamente a partir da biblioteca de conteúdo.
. Faça login no servidor vSphere.
. Navegue até o pool de recursos que você criou, para o cluster ou para o host onde deseja implantar o OVA.
. Clique com o botão direito do rato no local pretendido e selecione *Deploy OVF template...*.
+

NOTE: Nunca armazene ferramentas do ONTAP para máquinas virtuais VMware vSphere em armazenamentos de dados vVols que eles gerenciam.

. Selecione o arquivo OVA através da URL do arquivo _.ova_ ou navegue até a pasta onde o arquivo _.ova_ é salvo e clique em *Next*.
. Para implantar as ferramentas do ONTAP para VMware vSphere a partir da biblioteca de conteúdo:
+
.. Vá para sua biblioteca de conteúdo e clique no item da biblioteca que você deseja implantar.
.. Clique em *ações* > *Nova VM a partir deste modelo*


. Na janela *Selecione um nome e uma pasta* para a máquina virtual, insira o nome da máquina virtual e selecione o local da máquina virtual. Se você marcar a caixa de seleção que diz *Personalizar o hardware desta máquina virtual*, uma etapa chamada *Personalizar hardware* será ativada antes de você chegar à janela *Pronto para concluir*.
. Selecione um recurso de computador e clique em *Next*. Você pode optar por marcar a caixa de seleção para *ligar automaticamente a VM implantada*.
. Revise os detalhes do modelo e clique em *Next*.
. Leia e aceite o contrato de licença e clique em *Next*.
. Selecione o armazenamento para a configuração e os arquivos de disco e clique em *Next*.
. Selecione a rede de destino para cada rede de origem e clique em *Next*.
. Na janela *Personalizar modelo*, preencha os campos obrigatórios e clique em *seguinte*.
+
** As informações fornecidas aqui são validadas para padrões adequados durante o processo de instalação. Em caso de discrepância, uma mensagem de erro é exibida no console da Web e você é solicitado a corrigir qualquer informação incorreta fornecida.
** Os nomes dos hosts devem consistir em letras maiúsculas (A-Z), letras minúsculas (a-z), dígitos (0-9) ou carateres especiais hífen (-). Se você quiser configurar a pilha dupla, especifique o nome do host mapeado para o endereço IPv6.
+

NOTE: O Pure IPv6 não é compatível. O modo misto é suportado com VLAN com endereços IPv6 e IPv4.



. Na janela *Personalizar hardware*, você deve habilitar o hot add da CPU e o hot plug da memória.
. Revise os detalhes na janela *Pronto para concluir*, selecione *concluir*.
+
À medida que a tarefa de implantação é criada, o progresso é mostrado na barra de tarefas do vSphere.

. Ligue a VM após a conclusão da tarefa.
+

NOTE: Antes de ligar, certifique-se de que a VM tem plugins ativos ativados para CPU e memória.



Você pode acompanhar o andamento da instalação no console da Web da VM.

Em caso de discrepâncias nos valores inseridos no formulário OVF, uma caixa de diálogo solicitará que você tome medidas corretivas. Faça as alterações necessárias dentro da caixa de diálogo, utilizando o botão Tab para navegar e selecione "OK". Você tem três tentativas para corrigir quaisquer problemas. Se os problemas persistirem após três tentativas, o processo de instalação cessará e é recomendável que você tente novamente a instalação em uma nova VM.
