---
permalink: deploy/prerequisites.html 
sidebar: sidebar 
keywords: ONTAP tools requirements, configuration limits, supported versions, sizing 
summary: Revise as versões suportadas, o dimensionamento, os requisitos de porta e os limites de configuração antes de implementar ONTAP tools for VMware vSphere. 
---
= Ferramentas ONTAP para requisitos e limites de configuração do VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Revise as versões suportadas, o dimensionamento, os requisitos de porta e os limites de configuração antes de implementar ONTAP tools for VMware vSphere.

Implante ONTAP tools for VMware vSphere em um ambiente vSphere compatível que inclua hosts ESXi e VMware vCenter Server Virtual Appliance (vCSA).



[[system-requirements]]
== Requisitos do sistema

* * Requisitos de espaço do pacote de instalação por nó*
+
** 15 GB para instalações com provisionamento reduzido
** 348 GB para instalações com provisionamento espesso


* *Requisitos de dimensionamento do sistema host* A tabela abaixo mostra a CPU, memória e espaço de disco recomendados por nó para cada tamanho de implantação. Para implantações de alta disponibilidade (HA), implante três nós.


|===


| *Tipo de implantação* | *CPUs por nó* | *Memória (GB) por nó* | *Espaço em disco (GB) de espessura provisionado por nó* 


| Extra pequeno (XS) | 6 | 12 | 350 


| Pequeno | 9 | 18 | 350 


| Média | 13 | 26 | 350 


| Grande | 17 | 34 | 350 
|===

NOTE: O tamanho de implantação grande é suportado apenas para configuração HA.


NOTE: Quando o backup está ativado, cada cluster de ONTAP tools precisa de 50 GB adicionais de espaço no datastore onde as máquinas virtuais estão implantadas. Portanto, non-HA requer 400 GB e HA requer 1100 GB de espaço no total.



[[minimum-storage-and-application-requirements]]
== Requisitos mínimos de storage e aplicativos

|===
| Storage, host e aplicações | Requisitos de versão 


| Sistemas ONTAP | 9.16.1, 9.17.1, 9.18.1, 9.19.1 


| Hosts ESXi gerenciados pelas ONTAP tools | 7.0.3 em diante 


| vCenter Server instâncias gerenciadas por ONTAP tools | 8.0U3 em diante 


| Fornecedor VASA | 3,0 


| Aplicação OVA | 10,6 


| Host ESXi usado para implantar a máquina virtual ONTAP tools | 7.0U3 e 8.0U3 


| vCenter Server usado para implantar a máquina virtual ONTAP tools | 7,0 e 8,0 
|===

NOTE: A partir do ONTAP tools for VMware vSphere 10.4, a versão do hardware da máquina virtual muda de 10 para 17.

A ferramenta de Matriz de interoperabilidade (IMT) contém as informações mais recentes sobre as versões suportadas do ONTAP, vCenter Server, hosts ESXi e aplicativos de plug-in.

https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT["Ferramenta de Matriz de interoperabilidade"^]



[[port-requirements]]
== Requisitos portuários

A tabela a seguir descreve as portas de rede utilizadas pela NetApp e suas finalidades. Existem três tipos diferentes de portas:

* Portas externas: Essas portas são acessíveis de fora do cluster ou nó do Kubernetes. Eles permitem que os serviços se comuniquem com redes ou usuários externos, possibilitando a integração com sistemas fora do ambiente de cluster.
* Portas entre nós: Essas portas permitem a comunicação entre nós dentro do cluster Kubernetes. Elas são necessárias para operações do cluster, como troca de dados e coordenação entre nós. Em implantações com um único nó, as portas entre nós são usadas apenas dentro do próprio nó e não exigem acesso externo. Permita o tráfego entre nós apenas de redes confiáveis do cluster e bloqueie o acesso à internet com regras de firewall.
* Portas internas: Essas portas comunicam-se dentro do cluster Kubernetes usando endereços ClusterIP. Eles não são expostos externamente e não precisam ser adicionados às regras do firewall.



NOTE: Certifique-se de que todos os nós das ferramentas ONTAP residam na mesma sub-rede para manter uma comunicação ininterrupta entre si.

Clique para expandir ou recolher a tabela de requisitos de porta.

[%collapsible]
====
|===
| *Nome do serviço/componente* | *Porto* | *Protocolo* | *Tipo de porta* | *Descrição* 


| serviço ntv-gateway (LB) | 443, 8443 | TCP | Externo | Porta de passagem para comunicação de entrada do serviço VASA Provider. O certificado autoassinado do provedor VASA e o certificado CA personalizado são hospedados nesta porta. 


| SSH | 22 | TCP | Externo | Shell seguro para login remoto em servidores e execução de comandos. 


| servidor rke2 | 9345 | TCP | Inter-nó | API supervisora RKE2 (Restringir a redes confiáveis). 


| kube-apiserver | 6443 | TCP | Inter-nó | Porta do servidor da API do Kubernetes (Restringir a redes confiáveis). 


| rpcbind/portmapper | 111 | TCP/UDP | Inter-nó | Utilizado para comunicação RPC entre serviços. 


| núcleos (DNS) | 53 | TCP/UDP | Inter-nó | Serviço de Sistema de Nomes de Domínio (DNS) para resolução de nomes dentro do cluster. 


| NTP | 123 | UDP | Inter-nó | Protocolo de Tempo de Rede (NTP) para sincronização de tempo. 


| etcd | 2379, 2380, 2381 | TCP | Inter-nó | Armazenamento de chave-valor para dados de cluster. 


| kube-vip | 2112 | TCP | Inter-nó | Porta do servidor da API do Kubernetes. 


| kubelet | 10248, 10250 | TCP | Inter-nó | Componente do Kubernetes 


| kube-controlador | 10257 | TCP | Inter-nó | Componente do Kubernetes 


| controlador de nuvem | 10258 | TCP | Inter-nó | Componente do Kubernetes 


| kube-scheduler | 10259 | TCP | Inter-nó | Componente do Kubernetes 


| kube-proxy | 10249, 10256 | TCP | Inter-nó | Componente do Kubernetes 


| nó-calico | 9091, 9099 | TCP | Inter-nó | Componente de rede Calico. 


| containerd | 10010 | TCP | Inter-nó | Serviço daemon de contêiner. 


| VXLAN (Flanela) | 8472 | UDP | Inter-nó | Rede sobreposta para comunicação entre pods. 
|===

NOTE: Para implantações de alta disponibilidade (HA), certifique-se de que a porta UDP 8472 esteja aberta entre todos os nós. Esta porta permite a comunicação entre pods em diferentes nós; bloqueá-la interromperá a rede entre os nós.

====


[[configuration-limits-for-vvol-datastores]]
== Limites de configuração para vVol datastores

Utilize a tabela a seguir como guia para configurar as ferramentas ONTAP para VMware vSphere.

|===


| *Implantação* | *Tipo* | *Número de vVols* | *Número de hosts* 


| Não HA | Pequeno (S) | até 12K | 32 


| Não HA | Médio (M) | até 24K | 64 


| HA | Pequeno (S) | até 24K | 64 


| HA | Médio (M) | até 50K | 128 


| HA | Grande (L) | até 100K | 256 
|===

NOTE: A contagem de hosts na tabela representa o total combinado em todos os vCenters conectados.



[[configuration-limits-for-vmfs-and-nfs-datastores]]
== Limites de configuração para datastores VMFS e NFS

Os limites de configuração listados nesta seção são validados e suportados pela NetApp. Os limites reais podem variar dependendo do seu ambiente e carga de trabalho. Exceder esses limites pode afetar o desempenho ou a capacidade de suporte e não é recomendado. Considere o seguinte ao analisar a tabela:

* A recuperação de desastres (DR) de máquinas virtuais é configurada usando políticas síncronas, assíncronas ou de sincronização estrita. DR não é compatível com o protocolo NVMe.
* A proteção de cluster de hosts ESXi usa SnapMirror Active Sync, que não suporta implantações multi-vCenter.
* As ONTAP tools restringem apenas o número de hosts ESXi e datastores com base no tamanho da implementação. Não há restrições quanto ao número de servidores vCenter que podem ser conectados às ONTAP tools.
* ONTAP tools realiza a descoberta paralela de todos os objetos de armazenamento. Os limites de configuração para objetos de armazenamento ONTAP se aplicam independentemente do número de objetos em uso ativo.
* ONTAP tools não impõe um limite ao número de vCenter Servers que podem ser integrados. Os limites de configuração são determinados pelo número de hosts e datastores suportados, conforme detalhado na tabela a seguir.


|===
| Implantação | Número de datastores VMFS e NFS | Número de datastores VMFS com DR habilitado | Número de hosts 


| Extra pequeno | 50 | 50 | 16 


| Não-HA pequeno | 200 | 80 | 32 


| Meio não-HA | 250 | 100 | 32 


| HA Extra pequeno | 200 | 100 | 32 


| HA pequena | 350 | 200 | 64 


| HA média | 600 | 200 | 128 


| HA grande | 1024 | 250 | 256 
|===


[[ontap-tools-for-vmware-vsphere-storage-replication-adapter-sra]]
== Ferramentas do ONTAP para VMware vSphere - adaptador de replicação de armazenamento (SRA)

A tabela a seguir mostra os números suportados por instância do VMware Live Site Recovery usando as ferramentas do ONTAP para VMware vSphere.

|===
| *vCenter tamanho da implantação* | *Pequeno* | *Médio* 


| Número total de máquinas virtuais configuradas para proteção usando replicação baseada em array | 2000 | 5000 


| Número total de grupos de proteção de replicação baseados em array | 250 | 250 


| Número total de grupos de proteção por plano de recuperação | 50 | 50 


| Número de datastores replicados | 255 | 255 


| Número de VMs | 4000 | 7000 
|===
A tabela a seguir mostra o número de instâncias do VMware Live Site Recovery e o tamanho correspondente de implementação das ONTAP tools for VMware vSphere.

|===


| *Número de instâncias de recuperação do VMware Live Site* | *Tamanho da implantação das ONTAP tools* 


| Até 4 | Pequeno 


| 4 a 8 | Média 


| Mais de 8 | Grande 
|===
Para obter mais informações, https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/overview/site-recovery-manager-system-requirements/operational-limits-of-site-recovery-manager.html["Limites operacionais da recuperação do VMware Live Site"] consulte .
