---
permalink: deploy/prerequisites.html 
sidebar: sidebar 
keywords: ONTAP tools,Storage Replication Adapter 
summary: Antes de implantar as ferramentas do ONTAP para o VMware vSphere, você deve estar familiarizado com os requisitos de espaço para o pacote de implantação e alguns requisitos básicos do sistema de host. 
---
= Ferramentas ONTAP para requisitos e limites de configuração do VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de implantar as ferramentas do ONTAP para o VMware vSphere, você deve estar familiarizado com os requisitos de espaço para o pacote de implantação e alguns requisitos básicos do sistema de host.

Você pode usar as ferramentas do ONTAP para VMware vSphere com o VMware vCenter Server Virtual Appliance (vCSA). Você deve implantar as ferramentas do ONTAP para o VMware vSphere em um cliente vSphere compatível que inclua o sistema ESXi.



== Requisitos do sistema

* * Requisitos de espaço do pacote de instalação por nó*
+
** 15 GB para instalações com provisionamento reduzido
** 348 GB para instalações com provisionamento espesso


* *Requisitos de dimensionamento do sistema host* A tabela abaixo mostra a memória recomendada para cada tamanho de implantação. Para implantações de alta disponibilidade (HA), você precisa de três vezes o tamanho do dispositivo listado.


|===


| *Tipo de implantação* | *CPUs por nó* | *Memória (GB) por nó* | *Espaço em disco (GB) de espessura provisionado por nó* 


| Pequeno | 9 | 18 | 350 


| Média | 13 | 26 | 350 


| OBSERVAÇÃO: A implantação grande é apenas para configuração de HA. | 17 | 34 | 350 
|===

NOTE: Quando o backup está habilitado, cada cluster de ferramentas do ONTAP precisa de mais 50GB MB de espaço no armazenamento de dados onde as VMs são implantadas. Portanto, o não-HA requer 400 GB e o HA requer 1100 GB de espaço no total.



== Requisitos mínimos de storage e aplicativos

|===
| Storage, host e aplicações | Requisitos de versão 


| ONTAP | 9.15.1, 9.16.0, 9.16.1, 9.17.0 e 9.17.1 


| As ferramentas do ONTAP suportaram os hosts ESXi | 7.0.3 em diante 


| As ferramentas do ONTAP suportaram o vCenter Server | 7.0U3 em diante 


| Fornecedor VASA | 3,0 


| Aplicação OVA | 10,5 


| Host ESXi para implantar a máquina virtual ONTAP Tools | 7.0U3 e 8.0U3 


| VCenter Server para implantar a máquina virtual das ferramentas do ONTAP | 7,0 e 8,0 
|===

NOTE: A partir das ferramentas do ONTAP para VMware vSphere 10,4, o hardware da máquina virtual é alterado da versão 10 para 17.

A ferramenta de Matriz de interoperabilidade (IMT) contém as informações mais recentes sobre as versões suportadas do ONTAP, vCenter Server, hosts ESXi e aplicativos de plug-in.

https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT["Ferramenta de Matriz de interoperabilidade"^]



== Requisitos portuários

A tabela a seguir descreve as portas de rede utilizadas pela NetApp e suas finalidades. Existem três tipos diferentes de portas:

* Portas externas: Essas portas são acessíveis de fora do cluster ou nó do Kubernetes. Eles permitem que os serviços se comuniquem com redes ou usuários externos, possibilitando a integração com sistemas fora do ambiente de cluster.
* Portas entre nós: Essas portas permitem a comunicação entre os nós dentro do cluster Kubernetes. São necessários para tarefas em cluster, como compartilhamento de dados e trabalho em conjunto. Em implantações com um único nó, as portas entre nós são usadas apenas dentro do próprio nó e não precisam de acesso externo. As portas entre nós podem aceitar tráfego de fora do cluster. Bloqueie o acesso à internet das portas entre nós usando regras de firewall.
* Portas internas: Essas portas comunicam-se dentro do cluster Kubernetes usando endereços ClusterIP. Eles não são expostos externamente e não precisam ser adicionados às regras do firewall.



NOTE: Certifique-se de que todos os nós das ferramentas ONTAP residam na mesma sub-rede para manter uma comunicação ininterrupta entre si.

Clique para expandir ou recolher a tabela de requisitos de porta.

[%collapsible]
====
|===
| *Nome do serviço/componente* | *Porto* | *Protocolo* | *Tipo de porta* | *Descrição* 


| serviço ntv-gateway (LB) | 443, 8443 | TCP | Externo | Porta de passagem para comunicação de entrada do serviço VASA Provider. O certificado autoassinado do provedor VASA e o certificado CA personalizado são hospedados nesta porta. 


| SSH | 22 | TCP | Externo | Shell seguro para login remoto em servidores e execução de comandos. 


| servidor rke2 | 9345 | TCP | Inter-nó | API supervisora RKE2 (Restringir a redes confiáveis). 


| kube-apiserver | 6443 | TCP | Inter-nó | Porta do servidor da API do Kubernetes (Restringir a redes confiáveis). 


| rpcbind/portmapper | 111 | TCP/UDP | Inter-nó | Utilizado para comunicação RPC entre serviços. 


| núcleos (DNS) | 53 | TCP/UDP | Inter-nó | Serviço de Sistema de Nomes de Domínio (DNS) para resolução de nomes dentro do cluster. 


| NTP | 123 | UDP | Inter-nó | Protocolo de Tempo de Rede (NTP) para sincronização de tempo. 


| etcd | 2379, 2380, 2381 | TCP | Inter-nó | Armazenamento de chave-valor para dados de cluster. 


| kube-vip | 2112 | TCP | Inter-nó | Porta do servidor da API do Kubernetes. 


| kubelet | 10248, 10250 | TCP | Inter-nó | Componente do Kubernetes 


| kube-controlador | 10257 | TCP | Inter-nó | Componente do Kubernetes 


| controlador de nuvem | 10258 | TCP | Inter-nó | Componente do Kubernetes 


| kube-scheduler | 10259 | TCP | Inter-nó | Componente do Kubernetes 


| kube-proxy | 10249, 10256 | TCP | Inter-nó | Componente do Kubernetes 


| nó-calico | 9091, 9099 | TCP | Inter-nó | Componente de rede Calico. 


| containerd | 10010 | TCP | Inter-nó | Serviço daemon de contêiner. 


| VXLAN (Flanela) | 8472 | UDP | Inter-nó | Rede sobreposta para comunicação entre pods. 
|===

NOTE: Para implantações de alta disponibilidade (HA), certifique-se de que a porta UDP 8472 esteja aberta entre todos os nós. Esta porta permite a comunicação entre pods em diferentes nós; bloqueá-la interromperá a rede entre os nós.

====


== Limites de configuração para implantar as ferramentas do ONTAP para o VMware vSphere

Você pode usar a tabela a seguir como um guia para configurar as ferramentas do ONTAP para o VMware vSphere.

|===


| *Implantação* | *Tipo* | *Número de vVols* | *Número de hosts* 


| Não HA | Pequeno (S) | 12K | 32 


| Não HA | Médio (M) | 24K | 64 


| Alta disponibilidade | Pequeno (S) | 24K | 64 


| Alta disponibilidade | Médio (M) | 50k | 128 


| Alta disponibilidade | Grande (L) | 100k | 256 [NOTA] As contagens de hosts na tabela representam o total combinado em todos os vCenters conectados. 
|===


== Ferramentas do ONTAP para VMware vSphere - adaptador de replicação de armazenamento (SRA)

A tabela a seguir mostra os números suportados por instância do VMware Live Site Recovery usando as ferramentas do ONTAP para VMware vSphere.

|===
| * Tamanho da implantação do vCenter* | *Pequeno* | *Médio* 


| Número total de máquinas virtuais configuradas para proteção usando replicação baseada em array | 2000 | 5000 


| Número total de grupos de proteção de replicação baseados em array | 250 | 250 


| Número total de grupos de proteção por plano de recuperação | 50 | 50 


| Número de datastores replicados | 255 | 255 


| Número de VMs | 4000 | 7000 
|===
A tabela a seguir mostra o número de VMware Live Site Recovery e as ferramentas ONTAP correspondentes para o tamanho de implantação do VMware vSphere.

|===


| *Número de instâncias de recuperação do VMware Live Site* | *Tamanho de implantação de ferramentas ONTAP* 


| Até 4 | Pequeno 


| 4 a 8 | Média 


| Mais de 8 | Grande 
|===
Para obter mais informações, https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/overview/site-recovery-manager-system-requirements/operational-limits-of-site-recovery-manager.html["Limites operacionais da recuperação do VMware Live Site"] consulte .
