---
permalink: protect/configure-protection-groups.html 
sidebar: sidebar 
keywords:  
summary: Você deve criar grupos de proteção para proteger um grupo de máquinas virtuais no site protegido. 
---
= Configurar sites protegidos e de recuperação
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve criar grupos de proteção para proteger um grupo de máquinas virtuais no site protegido.

Ao adicionar um novo repositório de dados, você pode incluí-lo no grupo de repositórios de dados existente ou adicionar um novo repositório de dados e criar um novo volume ou grupo de consistência para proteção. Após adicionar um novo repositório de dados a um grupo de consistência ou volume protegido, atualize o SnapMirror e execute a descoberta de armazenamento nos sites protegido e de recuperação. Você pode executar a descoberta manualmente ou de acordo com uma programação para garantir que o novo repositório de dados seja detectado e protegido.



== Emparelhe locais protegidos e de recuperação

Você deve emparelhar os sites protegidos e de recuperação criados usando o vSphere Client para habilitar o Storage Replication Adapter (SRA) para descobrir os sistemas de armazenamento.


NOTE: O Adaptador de Replicação de Armazenamento (SRA) oferece suporte a fan-out com um relacionamento de sincronização do tipo Failover Duplex Automatizado e relacionamento assíncrono SnapMirror no grupo de consistência. No entanto, o fan-out com dois SnapMirror assíncronos no grupo de consistência ou SnapMirrors no volume não é suportado.

.Antes de começar
* Você deve ter o VMware Live Site Recovery instalado nos sites protegidos e de recuperação.
* Você deve ter o SRA instalado nos sites protegidos e de recuperação.


.Passos
. Na página inicial do vSphere Client, clique duas vezes no ícone *Site Recovery* e selecione *Sites*.
. Selecione *Objects* > *actions* > *Pair Sites*.
. Na caixa de diálogo *Emparelhar servidores do Gestor de recuperação de Site*, introduza o endereço do controlador de Serviços de Plataforma do site protegido e, em seguida, selecione *seguinte*.
. Na seção Selecionar vCenter Server, faça o seguinte:
+
.. Verifique se o vCenter Server do site protegido aparece como um candidato correspondente para emparelhar.
.. Insira as credenciais administrativas SSO e selecione *Finish*.


. Se solicitado, selecione *Sim* para aceitar os certificados de segurança.


.Resultado
A caixa de diálogo *Objetos* exibe os sites protegidos e de recuperação.



== Configurar grupos de proteção

.Antes de começar
Você deve garantir que ambos os sites de origem e destino estejam configurados para o seguinte:

* Mesma versão do VMware Live Site Recovery instalada
* Máquinas virtuais
* Emparelhados sites protegidos e de recuperação
* Os datastores de origem e destino devem ser montados nos respetivos sites


.Passos
. Faça login no vCenter Server e selecione *Site Recovery* > *Grupos de proteção*.
. No painel *grupos de proteção*, selecione *novo*.
. Especifique um nome e uma descrição para o grupo de proteção, direção e selecione *Next*.
. No campo *Tipo*, selecione a opção *Campo Tipo...* como grupos de armazenamento de dados (replicação baseada em matriz) para armazenamento de dados NFS e VMFS. O domínio de falha nada mais é do que SVMs com replicação habilitada. As SVMs que possuem apenas peering implementado e não apresentam problemas são exibidas.
. Na guia grupos de replicação, selecione o par de matrizes ativado ou os grupos de replicação que têm a máquina virtual configurada e, em seguida, selecione *Next*.
+
Todas as máquinas virtuais no grupo de replicação são adicionadas ao grupo de proteção.

. Você pode selecionar o plano de recuperação existente ou criar um novo selecionando *Adicionar ao novo plano de recuperação.*
. Na guia Pronto para concluir, revise os detalhes do grupo de proteção que você criou e selecione *concluir*.

