---
permalink: protect/configure-placeholder-datastores.html 
sidebar: sidebar 
keywords:  
summary: 'Configure um armazenamento de dados de espaço reservado para reservar espaço no inventário do vCenter no site de recuperação para máquinas virtuais (VMs) protegidas.  Os armazenamentos de dados de espaço reservado exigem capacidade mínima, porque as VMs de espaço reservado são pequenas e normalmente usam apenas algumas centenas de quilobytes.' 
---
= Configurar datastores de espaço reservado
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Configure um armazenamento de dados de espaço reservado para reservar espaço no inventário do vCenter no site de recuperação para máquinas virtuais (VMs) protegidas.  Os armazenamentos de dados de espaço reservado exigem capacidade mínima, porque as VMs de espaço reservado são pequenas e normalmente usam apenas algumas centenas de quilobytes.

.Antes de começar
* Certifique-se de que os locais protegidos e de recuperação estejam conectados.
* Verifique se os mapeamentos de recursos foram configurados.


.Passos
. Inicie sessão no vCenter Server e selecione *Site Recovery* > *Sites*.
. Selecione seu site protegido e selecione *Gerenciar*.
. Selecione *datastores de espaço* > *novo* na guia gerenciar para criar um novo datastore de espaço reservado.
. Selecione o datastore apropriado e selecione *OK*.
+

NOTE: Os armazenamentos de dados de espaço reservado podem residir em armazenamento local ou remoto, mas não exigem replicação.

. Repita as etapas de 3 a 5 para configurar um datastore de espaço reservado para o site de recuperação.

