---
permalink: protect/update-credentials.html 
sidebar: sidebar 
keywords: SRA credentials, updating 
summary: Para que o VMware Live Site Recovery se comunique com o SRA, você deve atualizar as credenciais do SRA no servidor VMware Live Site Recovery se tiver modificado as credenciais. 
---
= Atualizar credenciais SRA nas ferramentas ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para que o VMware Live Site Recovery se comunique com o SRA, você deve atualizar as credenciais do SRA no servidor VMware Live Site Recovery se tiver modificado as credenciais.

.Antes de começar
Você deve ter executado as etapas mencionadas no link:../protect/configure-on-srm-appliance.html["Configurando o SRA no VMware Live Site Recovery Appliance"]tópico .

.Passos
. Execute os seguintes comandos para excluir as credenciais armazenadas em cache das ferramentas ONTAP da máquina VMware Live Site Recovery:
+
.. `sudo su <enter root password>`
.. `docker ps`
.. `docker exec -it <container_id> sh`
.. `cd conf/`
.. `rm -rf *`


. Execute o comando Perl para configurar o SRA com as novas credenciais:
+
.. `cd ..`
.. `perl command.pl -I --otv-ip <OTV_IP>:8443 --otv-username <OTV_ADMIN_USERNAME> --otv-password <OTV_ADMIN_PASSWORD> --vcenter-guid <VCENTER_GUID>` Você precisa ter uma única cotação em torno do valor da senha.
+
Uma mensagem de sucesso confirmando que as credenciais de armazenamento foram salvas é exibida. O SRA pode se comunicar com o servidor SRA usando o endereço IP, a porta e as credenciais fornecidas.







== Reconfigure vCenter no appliance VMware Live Site Recovery após uma alteração de certificado

Se o certificado do vCenter for alterado, por exemplo, após uma atualização do vCenter, você poderá encontrar um erro de incompatibilidade de impressão digital na extensão Site Recovery. Execute as seguintes etapas para resolvê-lo.

.Passos
. Reconfigure vCenter no appliance VMware Live Site Recovery
+
.. Abra a interface de gerenciamento do VMware Live Site Recovery appliance em um navegador: `\https://<SRM_IP>:5480`
.. Selecione a aba *Resumo*.
.. Selecione *Reconfigurar* para a conexão do servidor vCenter.
+
Isso busca e aceita a impressão digital do certificado mais recente de vCenter.



. Reconectar o emparelhamento do site (se o erro persistir)
+
Se o erro de incompatibilidade de impressão digital persistir após a reconfiguração:

+
.. Faça login na interface de usuário do vCenter.
.. Acesse a extensão *Site Recovery*.
.. Localize a seção *Emparelhamento de Sites*.
.. Selecione *Reconectar* para restabelecer o emparelhamento do site com o certificado atualizado.



