---
permalink: concepts/ontap-tools-overview.html 
sidebar: sidebar 
keywords: ONTAP tools overview, virtual machine lifecycle, VASA Provider, disaster recovery 
summary: Saiba como ONTAP tools for VMware vSphere oferece suporte ao gerenciamento de ciclo de vida do storage de máquina virtual, ao provisionamento de datastore e à recuperação de desastres. 
---
= Saiba mais sobre as ferramentas do ONTAP para VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphere é um conjunto de ferramentas para gerenciamento de ciclo de vida de máquina virtual. Ele se integra ao ecossistema VMware para simplificar o provisionamento de datastores e fornecer proteção básica e recuperação de desastres para máquinas virtuais. Implantado como um Open Virtual Appliance (OVA), utiliza microsserviços orientados a eventos e com escalabilidade horizontal para oferecer desempenho confiável em grande escala.

As ONTAP tools for VMware vSphere oferecem suporte a:

* Recursos principais da máquina virtual (VM), como proteção e recuperação de desastres
* Provedor VASA para gerenciamento baseado em políticas de armazenamento
* Gerenciamento baseado em política de storage
* Adaptador de replicação de armazenamento (SRA)


.Alta disponibilidade para ONTAP tools for VMware vSphere
As ONTAP tools for VMware vSphere oferecem suporte de alta disponibilidade (HA) para ajudar a manter a operação ininterrupta durante falhas.

A solução HA ajuda você a se recuperar rapidamente dos seguintes tipos de interrupções:

* Falha de host - Somente uma falha de nó único é suportada.
* Falha de rede
* Falha na máquina virtual (sistema operacional convidado)
* Falha no aplicativo (ferramentas ONTAP )


Você não precisa executar nenhuma configuração adicional para habilitar o HA para ONTAP tools for VMware vSphere.

[NOTE]
====
As ONTAP tools for VMware vSphere não oferecem suporte ao vCenter HA.

====
Para usar o recurso de HA, certifique-se de que o adicionar sem desligamento de CPU e o hot-plug de memória estejam habilitados durante a implantação ou nas configurações da máquina virtual.
