---
permalink: configure/add-storage-backend.html 
sidebar: sidebar 
keywords:  
summary: Os backends de armazenamento são sistemas que os hosts ESXi usam para armazenamento de dados. 
---
= Adicionar backend de armazenamento às ferramentas ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilize as ONTAP tools for VMware vSphere para adicionar e gerenciar backends de armazenamento para seus hosts ESXi.  Você pode integrar clusters ou SVMs, habilitar o suporte a MetroCluster e validar certificados para conectividade segura.  Você pode configurar os backends de armazenamento usando o ONTAP Tools Manager ou o cliente vSphere, monitorar o status do certificado e redescobrir recursos manualmente após alterações no cluster.

Para adicionar um backend de armazenamento localmente, use as credenciais do cluster ou do SVM na interface das ferramentas ONTAP .  Os servidores de armazenamento local estão disponíveis apenas para o vCenter Server selecionado. As ferramentas ONTAP mapeiam SVMs para o vCenter Server para gerenciamento de armazenamento de dados vVols ou VMFS.  Para datastores VMFS e fluxos de trabalho SRA, você pode usar credenciais SVM sem mapear um cluster globalmente.

Para adicionar um backend de armazenamento global, use as credenciais do cluster ONTAP no Gerenciador de ferramentas ONTAP .  Os backends de armazenamento globais permitem fluxos de trabalho de descoberta para identificar os recursos de cluster necessários para o gerenciamento de vVols.  Em ambientes multitenant, você pode adicionar um usuário SVM localmente para gerenciar datastores vVols .

Se o suporte a MetroCluster estiver habilitado no ONTAP, integre os clusters de origem e destino como backends de armazenamento locais ou globais.

.Antes de começar
Verifique se o certificado inclui um campo Nome Alternativo de Assunto (SAN) válido.  Os sistemas ONTAP usam o campo SAN para identificar LIFs de gerenciamento de cluster e SVM.

[role="tabbed-block"]
====
.Usando o Gerenciador de ferramentas do ONTAP
--

NOTE: Em uma configuração de alocação a vários clientes, é possível adicionar um cluster de back-end de storage globalmente e SVM localmente para usar as credenciais de usuário do SVM.

.Passos
. Inicie o Gerenciador de ferramentas do ONTAP a partir de um navegador da Web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Faça login com as ferramentas do ONTAP para as credenciais de administrador do VMware vSphere fornecidas durante a implantação.
. Selecione *backends de armazenamento* na barra lateral.
. Adicione o back-end de armazenamento e forneça o endereço IP do servidor ou FQDN, nome de usuário e detalhes de senha.
+

NOTE: LIFs de gerenciamento de endereços IPv4 e IPv6 são compatíveis.

. Obtenha os certificados do cluster ONTAP automaticamente e autorize o certificado ou carregue-o manualmente navegando até seu local.
+

NOTE: Se necessário, você pode desabilitar a validação do Nome Alternativo do Assunto (SAN) no console de manutenção. Para obter instruções, consultelink:../manage/change-valid-flag.html["Alterar sinalizador de validação de certificado"] .

. Se o backend de armazenamento adicionado fizer parte de uma configuração do MetroCluster , o ONTAP Tools Manager mostrará uma mensagem pop-up para adicionar o cluster emparelhado.  Selecione *Adicionar* e forneça os detalhes para o backend de armazenamento peer do MetroCluster .
+

NOTE: Depois que o sistema ONTAP executar uma alternância e uma reversão, execute a descoberta de ferramentas ONTAP manualmente.



--
.Usando a interface de usuário do cliente vSphere
--

NOTE: Os datastores vVols não suportam a adição direta de um usuário SVM por meio da interface de usuário do cliente vSphere.

. Faça login no cliente vSphere.
. Na página atalhos, selecione *Ferramentas do NetApp ONTAP* na seção plug-ins.
. Selecione *backends de armazenamento* na barra lateral.
. Adicione o back-end de armazenamento e forneça o endereço IP do servidor, nome de usuário, senha e detalhes da porta.
+

NOTE: Você pode adicionar um backend de armazenamento usando credenciais baseadas em cluster com LIFs de gerenciamento IPv4 ou IPv6.  Para adicionar um usuário SVM diretamente, forneça credenciais baseadas em SVM junto com um LIF de gerenciamento de SVM.  Se um cluster já estiver integrado, você não poderá integrar um usuário SVM desse cluster novamente.

. Obtenha os certificados do cluster ONTAP automaticamente e autorize o certificado ou carregue-o manualmente navegando até seu local.
. Se o backend de armazenamento adicionado fizer parte da configuração do MetroCluster , as ferramentas ONTAP exibirão a tela *Adicionar peer do MetroCluster *.  Selecione *Adicionar peer* para adicionar o backend de armazenamento peer.
+

NOTE: Depois que o sistema ONTAP executar uma alternância e uma reversão, execute a descoberta de ferramentas ONTAP manualmente.



.O que vem a seguir?
As ferramentas ONTAP atualizam a lista para mostrar o novo backend de armazenamento.

--
====
As ferramentas ONTAP listam o backend de armazenamento recém-adicionado na página *Backends de armazenamento*.  Se um certificado expirar em 30 dias ou menos, as ferramentas ONTAP mostrarão um aviso na coluna de data de expiração do certificado.  Após a expiração, as ferramentas ONTAP marcam o backend de armazenamento como desconhecido porque ele não consegue se conectar ao sistema de armazenamento.

.Informações relacionadas
https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_sw_config_configure_clusters.html["Configurando os clusters em uma configuração MetroCluster"]
