---
permalink: configure/add-vcenter.html 
sidebar: sidebar 
keywords:  
summary: Adicione instâncias do vCenter Server às ferramentas do ONTAP para o VMware vSphere para configurar, gerenciar e proteger seus datastores virtuais no ambiente do vCenter Server. 
---
= Adicionar instâncias do vCenter Server às ferramentas ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Adicione instâncias do vCenter Server às ferramentas do ONTAP para o VMware vSphere para configurar, gerenciar e proteger seus datastores virtuais no ambiente do vCenter Server. Ao adicionar várias instâncias do vCenter Server, certificados de CA personalizados são necessários para comunicação segura entre as ferramentas ONTAP e cada vCenter Server.

.Sobre esta tarefa
As ferramentas ONTAP se integram ao vCenter Server para executar tarefas de armazenamento como provisionamento, snapshots e proteção de dados diretamente do cliente vSphere.

.Passos
. Abra um navegador da web e acesse o URL: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Faça login com as ferramentas do ONTAP para as credenciais de administrador do VMware vSphere fornecidas durante a implantação.
. Selecione *vCenters* > *Add* para integrar as instâncias do vCenter Server. Forneça seu endereço IP ou nome de host do vCenter, nome de usuário, senha e detalhes da porta.
. Nas opções avançadas, obtenha o certificado do vCenter Server automaticamente (autorize-o) ou carregue-o manualmente.
+

NOTE: Você não precisa de uma conta de administrador para adicionar instâncias do vCenter às ferramentas do ONTAP. Você pode criar uma função personalizada sem a conta de administrador com permissões limitadas. link:../concepts/rbac-vcenter-use.html["Use o RBAC do vCenter Server com as ferramentas do ONTAP para VMware vSphere 10"]Consulte para obter detalhes.



Adicionar uma instância do vCenter Server às ferramentas do ONTAP aciona automaticamente as seguintes ações:

* As ferramentas ONTAP registram o plug-in do cliente vCenter como um plug-in remoto.
* Os Privileges personalizados para os plug-ins e APIs são aplicados à instância do vCenter Server.
* Funções personalizadas são criadas para gerenciar os usuários.
* O plug-in aparece como um atalho na interface do usuário do vSphere.

