---
permalink: configure/configure-network-access.html 
sidebar: sidebar 
keywords: configure network access, ONTAP export policy, ESXi host IP allowlist, ONTAP tools mount access 
summary: Configure o acesso à rede para controlar quais endereços IP de hosts ESXi são adicionados às políticas de exportação em ONTAP tools. 
---
= Configure o acesso à rede nas ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Por padrão, todos os endereços IP descobertos no host ESXi são adicionados automaticamente à política de exportação, a menos que você configure o acesso à rede.  Você pode modificar a política de exportação para permitir o acesso somente a partir de endereços IP específicos.  Se um host ESXi excluído tentar uma operação de montagem, a operação falhará.

.Passos
. Faça login no cliente vSphere.
. Selecione *Ferramentas do NetApp ONTAP* na página de atalhos na seção plug-ins.
. No painel esquerdo das ferramentas ONTAP , vá para *Configurações* > *Gerenciar acesso à rede* > *Editar*.
+
Para adicionar vários endereços IP, separe a lista com vírgulas, intervalo, CIDR (Classless Inter-Domain Routing) ou uma combinação de todos os três.

. Selecione *Guardar*.

