---
permalink: configure/configure-esx-server-multipath-and-timeout-settings.html 
sidebar: sidebar 
keywords:  
summary: As ferramentas do ONTAP para VMware vSphere verificam e definem as configurações de multipathing do host ESXi e as configurações de tempo limite do HBA que funcionam melhor com os sistemas de armazenamento NetApp. 
---
= Configure as configurações do host ESXi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Configurar as configurações de multicaminho e tempo limite do servidor ESXi ajuda a manter a disponibilidade e a integridade dos dados.  Ele permite o failover automático para um caminho de armazenamento de backup se o caminho principal ficar indisponível.



== Configure as configurações multipath e timeout do servidor ESXi

As ferramentas do ONTAP para VMware vSphere verificam e definem as configurações de multipath do host ESXi e as configurações de tempo limite do HBA que funcionam melhor com os sistemas de armazenamento NetApp.

.Sobre esta tarefa
Esse processo pode levar algum tempo, dependendo da sua configuração e da carga do sistema.  Você pode ver o progresso no painel Tarefas recentes.

.Passos
. Na página inicial do VMware vSphere Web client, selecione *hosts and clusters*.
. Na página de atalhos do cliente da Web VMware vSphere, selecione *Ferramentas do NetApp ONTAP* na seção plug-ins.
. Vá para a placa *ESXi Host Compliance* na visão geral (painel) das ferramentas do ONTAP para o plug-in VMware vSphere.
. Selecione o link *Apply Recommended Settings* (aplicar configurações recomendadas).
. Na janela *Aplicar configurações de host recomendadas*, selecione os hosts que você deseja atualizar para usar as configurações recomendadas da NetApp e selecione *Avançar*.
+

NOTE: Você pode expandir o host ESXi para ver os valores atuais.

. Na página de definições, selecione os valores recomendados, conforme necessário.
. No painel de resumo, verifique os valores e selecione *Finish*. Você pode acompanhar o progresso no painel de tarefas recentes.




== Defina os valores do host ESXi

Use ONTAP tools for VMware vSphere para definir tempos limite e outros valores em hosts ESXi para desempenho e failover ideais.  Ele define esses valores com base nos testes da NetApp .

Você pode definir os seguintes valores em um host ESXi:



=== Definições do adaptador HBA/CNA

Define os seguintes parâmetros para valores padrão:

* Disk.QFullSampleSize
* Disk.QFullThreshold
* Tempos limite Emulex FC HBA
* Tempos limite do QLogic FC HBA




=== Definições MPIO

As configurações do MPIO escolhem os melhores caminhos para os sistemas de armazenamento NetApp .  As configurações do MPIO selecionam o melhor caminho e o utilizam.

Para ambientes de alto desempenho ou ao testar com um único armazenamento de dados LUN, ajuste a configuração de balanceamento de carga da política de seleção de caminho (PSP) round-robin (VMW_PSP_RR) para melhorar o desempenho.  Defina o valor padrão de IOPS de 1000 a 1.


NOTE: As configurações de MPIO não se aplicam aos protocolos NVMe, NVMe/FC e NVMe/TCP.



=== Definições NFS

|===


| Parâmetro | Defina este valor para... 


| NET.TcpipHeapSize | 32 


| NET.TcpipHeapMax | 1024 MB 


| NFS.MaxVolumes | 256 


| NFS41.MaxVolumes | 256 


| NFS.MaxQueueDepth | 128 ou superior 


| NFS.HeartbeatMaxFailures | 10 


| Frequência NFS.HeartbeatFrequency | 12 


| NFS.HeartbeatTimeout | 5 
|===