---
permalink: configure/configure-esx-server-multipath-and-timeout-settings.html 
sidebar: sidebar 
keywords:  
summary: As ferramentas do ONTAP para VMware vSphere verificam e definem as configurações de multipathing do host ESXi e as configurações de tempo limite do HBA que funcionam melhor com os sistemas de armazenamento NetApp. 
---
= Configure as configurações multipath e timeout do servidor ESXi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A configuração das configurações de multipath e timeout do servidor ESXi garante alta disponibilidade e integridade de dados, permitindo alternar perfeitamente para um caminho de armazenamento de backup se um caminho primário falhar.

As ferramentas do ONTAP para VMware vSphere verificam e definem as configurações de multipath do host ESXi e as configurações de tempo limite do HBA que funcionam melhor com os sistemas de armazenamento NetApp.

*Sobre esta tarefa*

Dependendo da configuração e da carga do sistema, esse processo pode levar muito tempo. O progresso da tarefa é exibido no painel tarefas recentes.

.Passos
. Na página inicial do VMware vSphere Web client, selecione *hosts and clusters*.
. Clique com o botão direito do Mouse em um host e selecione *Ferramentas do NetApp ONTAP* > *Atualizar dados do host*.
. Na página de atalhos do cliente da Web VMware vSphere, selecione *Ferramentas do NetApp ONTAP* na seção plug-ins.
. Vá para a placa *ESXi Host Compliance* na visão geral (painel) das ferramentas do ONTAP para o plug-in VMware vSphere.
. Selecione o link *Apply Recommended Settings* (aplicar configurações recomendadas).
. Na janela *Apply Recommended host settings* (aplicar configurações de host recomendadas), selecione os hosts que você deseja atualizar para estar em conformidade com as configurações recomendadas do NetApp e selecione *Next* (Avançar).
+

NOTE: Você pode expandir o host ESXi para ver os valores atuais.

. Na página de definições, selecione os valores recomendados, conforme necessário.
. No painel de resumo, verifique os valores e selecione *Finish*. Você pode acompanhar o progresso no painel de tarefas recentes.

