---
permalink: configure/create-datastore.html 
sidebar: sidebar 
keywords:  
summary: Quando você cria um armazenamento de dados no nível do cluster do host, as ferramentas ONTAP o montam em todos os hosts de destino e habilitam a ação somente se você tiver os privilégios necessários. 
---
= Crie um datastore
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando você cria um armazenamento de dados no nível do cluster do host, as ferramentas ONTAP o montam em todos os hosts de destino e habilitam a ação somente se você tiver os privilégios necessários.

*Interoperabilidade entre datastores nativos com vCenter Server e datastores gerenciados por ferramentas ONTAP*

A partir das ONTAP tools for VMware vSphere 10.4, as ferramentas ONTAP criam igroups aninhados para datastores, com igroups pais específicos para datastores e igroups filhos mapeados para os hosts.  Você pode criar igroups simples no ONTAP System Manager e usá-los para criar armazenamentos de dados VMFS sem usar ferramentas ONTAP . Consulte https://docs.netapp.com/us-en/ontap/san-admin/manage-san-initiators-task.html["Gerenciar iniciadores SAN e igroups"] para maiores informações.

Depois de integrar o armazenamento e executar a descoberta do armazenamento de dados, as ferramentas ONTAP alteram igroups simples em armazenamentos de dados VMFS para igroups aninhados.  Não é possível usar igroups simples anteriores para criar novos armazenamentos de dados.  Use a interface de ferramentas ONTAP ou a API REST para reutilizar igroups aninhados.

[role="tabbed-block"]
====
.Crie um datastore vVols
--
Começando com as ONTAP tools for VMware vSphere 10.3, você pode criar um armazenamento de dados vVols em sistemas ASA r2 com eficiência de espaço como thin.vVol.  O provedor VASA cria um contêiner e os pontos de extremidade de protocolo desejados ao criar o armazenamento de dados vVol.  O Provedor VASA não atribui nenhum volume de apoio a este contêiner.

.Antes de começar
* Certifique-se de que os agregados raiz não sejam mapeados para SVM.
* Certifique-se de que o Fornecedor VASA está registado no vCenter selecionado.
* No sistema de armazenamento ASA r2, o SVM deve ser mapeado para o agregado do usuário do SVM.


.Passos
. Faça login no cliente vSphere.
. Clique com o botão direito do mouse em um sistema host, cluster de host ou data center e selecione * Ferramentas NetApp ONTAP * > *Criar armazenamento de dados*.
. Selecione vVols *datastore type*.
. Insira as informações *nome do datastore* e *Protocolo*.
+

NOTE: O sistema ASA R2 dá suporte aos protocolos iSCSI e FC para vVols.

. Selecione a VM de armazenamento onde você deseja criar o datastore.
. Em opções avançadas:
+
** Se você selecionar a *Política de exportação personalizada*, certifique-se de executar a descoberta no vCenter para todos os objetos.  É recomendável que você não use esta opção.
** Você pode selecionar *Nome do grupo de iniciadores personalizados* para os protocolos iSCSI e FC.
+

NOTE: No sistema de armazenamento ASA r2 tipo SVM, as unidades de armazenamento (LUN/namespace) não são criadas porque o armazenamento de dados é apenas um contêiner lógico.



. No painel *atributos de armazenamento*, você pode criar novos volumes ou usar os volumes existentes. No entanto, você não pode combinar esses dois tipos de volumes para criar um datastore vVols.
+
Ao criar um novo volume, você pode habilitar o QoS no armazenamento de dados.  Por padrão, um volume é criado para cada solicitação criada por LUN.  Ignore esta etapa para datastores vVols em sistemas de armazenamento ASA r2.

. Reveja a sua seleção no painel *Summary* e selecione *Finish*.


--
.Criar um armazenamento de dados NFS
--
Um armazenamento de dados NFS conecta hosts ESXi ao armazenamento compartilhado usando o protocolo NFS.  Eles são simples e flexíveis e são usados em ambientes VMware vSphere.

.Passos
. Faça login no cliente vSphere.
. Clique com o botão direito do mouse em um sistema host, cluster de host ou data center e selecione * Ferramentas NetApp ONTAP * > *Criar armazenamento de dados*.
. Selecione NFS no campo *datastore type*.
. Insira o nome, o tamanho e as informações do protocolo do datastore no painel *Nome e protocolo*. Selecione *datastore cluster* e *Kerberos Authentication* nas opções avançadas.
+

NOTE: A autenticação Kerberos só está disponível quando o protocolo NFS 4,1 está selecionado.

. Selecione *Plataforma* e *Storage VM* no painel *Storage*.
. Se você selecionar *Política de exportação personalizada* nas opções avançadas, execute a descoberta no vCenter para todos os objetos.  É recomendável que você não use esta opção.
+

NOTE: Não é possível criar um armazenamento de dados NFS usando a política de volume raiz ou padrão do SVM.

+
** Nas opções avançadas, o botão de alternância *assimétrico* fica visível apenas se o desempenho ou a capacidade estiver selecionado na lista suspensa da plataforma.
** Ao escolher a opção *Qualquer* no menu suspenso da plataforma, você pode ver todas as SVMs no vCenter.  Plataforma e bandeira assimétrica não afetam a visibilidade.


. Selecione o agregado para criação de volume no painel *atributos de armazenamento*. Nas opções avançadas, escolha *reserva de espaço* e *Ativar QoS* conforme necessário.
. Revise as seleções no painel *Summary* e selecione *Finish*.


As ferramentas ONTAP criam o armazenamento de dados NFS e o montam em todos os hosts.

--
.Crie um datastore VMFS
--
VMFS é um sistema de arquivos em cluster para armazenar arquivos de máquinas virtuais.  Vários hosts ESXi podem acessar os mesmos arquivos de VM simultaneamente para recursos vMotion e Alta Disponibilidade.

Num cluster protegido:

* Você pode criar somente armazenamentos de dados VMFS.  Adicionar um armazenamento de dados VMFS a um cluster protegido o protege automaticamente.
* Não é possível criar um datastore em um data center com um ou mais clusters de host protegidos.
* Não é possível criar um armazenamento de dados em um host ESXi se o cluster do host pai estiver protegido por uma "política de Failover Duplex Automatizado" (configuração uniforme ou não uniforme).
* Você pode criar um datastore VMFS somente em um host ESXi protegido por uma relação assíncrona. Não é possível criar e montar um datastore em um host ESXi que faça parte de um cluster de host protegido pela política "Automated failover Duplex".


.Antes de começar
* Ative os serviços e LIFs para cada protocolo no lado do storage do ONTAP.
* Mapear o SVM para agregar usuário do SVM no sistema de storage ASA R2.
* Configure o host ESXi se estiver usando o protocolo NVMe/TCP:
+
.. Reveja o. https://www.vmware.com/resources/compatibility/detail.php?deviceCategory=san&productid=49677&releases_filter=589,578,518,508,448&deviceCategory=san&details=1&partner=399&Protocols=1&transportTypes=3&isSVA=0&page=1&display_interval=10&sortColumn=Partner&sortOrder=Asc["Guia de compatibilidade da VMware"]
+

NOTE: O VMware vSphere 7,0 U3 e versões posteriores são compatíveis com o protocolo NVMe/TCP. No entanto, é recomendável usar o VMware vSphere 8,0 e versões posteriores.

.. Verifique se o fornecedor da placa de interface de rede (NIC) oferece suporte à NIC ESXi com o protocolo NVMe/TCP.
.. Configure a placa de rede ESXi para NVMe/TCP de acordo com as especificações do fornecedor da placa de rede.
.. Ao usar a versão do VMware vSphere 7, siga as instruções no site da VMware https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-storage-7-0/about-vmware-nvme-storage/configure-adapters-for-nvme-over-tcp-storage/configure-vmkernel-binding-for-the-tcp-adapter.html["Configure a vinculação VMkernel para o adaptador NVMe sobre TCP"] para configurar a vinculação de portas NVMe/TCP. Ao usar a versão do VMware vSphere 8, siga https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/about-vmware-nvme-storage/configuring-nvme-over-tcp-on-esxi.html["Configurando o NVMe em TCP no ESXi"]o , para configurar a vinculação de porta NVMe/TCP.
.. Para a versão do VMware vSphere 7, siga as instruções na página https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-storage-7-0/about-vmware-nvme-storage/add-software-nvme-over-rdma-or-nvme-over-tcp-adapters.html["Habilite o NVMe em adaptadores de software RDMA ou NVMe em TCP"] para configurar adaptadores de software NVMe/TCP. Para a versão do VMware vSphere 8, siga https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/about-vmware-nvme-storage/configuring-nvme-over-rdma-roce-v2-on-esxi/add-software-nvme-over-rdma-or-nvme-over-tcp-adapters.html["Adicionar software NVMe em adaptadores RDMA ou NVMe em TCP"] para configurar os adaptadores de software NVMe/TCP.
.. Execute link:../configure/discover-storage-systems-and-hosts.html["Descubra sistemas de storage e hosts"] uma ação no host ESXi. Para obter mais informações, https://community.netapp.com/t5/Tech-ONTAP-Blogs/How-to-Configure-NVMe-TCP-with-vSphere-8-0-Update-1-and-ONTAP-9-13-1-for-VMFS/ba-p/445429["Como configurar o NVMe/TCP com o vSphere 8,0 Update 1 e o ONTAP 9.13,1 para datastores VMFS"] consulte .


* Se você estiver usando o protocolo NVME/FC, execute as seguintes etapas para configurar o host ESXi:
+
.. Se ainda não estiver habilitado, habilite o NVMe sobre Fabrics (NVMe-of) em seus hosts ESXi.
.. Zoneamento SCSI completo.
.. Certifique-se de que os hosts ESXi e o sistema ONTAP estejam conetados em uma camada física e lógica.




Para configurar um protocolo ONTAP SVM para FC, https://docs.netapp.com/us-en/ontap/san-admin/configure-svm-fc-task.html["Configurar um SVM para FC"] consulte .

Para obter mais informações sobre como usar o protocolo NVMe/FC com o VMware vSphere 8,0, https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_8.html["Configuração de host NVMe-of para ESXi 8.x com ONTAP"] consulte .

Para obter mais informações sobre como usar o NVMe/FC com o VMware vSphere 7,0, https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_8.html["Guia de configuração de host ONTAP NVMe/FC"] consulte e http://www.netapp.com/us/media/tr-4684.pdf["TR-4684"].

.Passos
. Faça login no cliente vSphere.
. Clique com o botão direito do mouse em um sistema host, cluster de host ou data center e selecione * Ferramentas NetApp ONTAP * > *Criar armazenamento de dados*.
. Selecione o tipo de armazenamento de dados VMFS.
. Insira o nome, o tamanho e as informações de protocolo do armazenamento de dados no painel *Nome e Protocolo*.  Para adicionar o novo armazenamento de dados a um cluster VMFS existente, selecione o cluster de armazenamento de dados em Opções avançadas.
. Selecione Storage VM (VM de armazenamento) no painel *Storage* (armazenamento). Forneça o *Nome do grupo de iniciadores personalizados* na seção *Opções avançadas* conforme necessário. Você pode escolher um grupo existente para o datastore ou criar um novo grupo com um nome personalizado.
+
Quando o protocolo NVMe/FC ou NVMe/TCP é selecionado, um novo subsistema de namespace é criado e usado para mapeamento de namespace.  As ferramentas ONTAP criam o subsistema de namespace usando o nome gerado automaticamente que inclui o nome do armazenamento de dados.  Você pode renomear o subsistema de namespace no campo *nome do subsistema de namespace personalizado* nas opções avançadas do painel *Armazenamento*.

. No painel *atributos de armazenamento*:
+
.. Selecione *agregar* nas opções suspensas.
+

NOTE: Para sistemas de armazenamento ASA r2, a opção *Agregar* não é mostrada porque o armazenamento é desagregado. Ao escolher um sistema de armazenamento ASA r2 do tipo SVM, a página de atributos de armazenamento mostra as opções para habilitar a QoS.

.. As ferramentas ONTAP criam uma unidade de armazenamento (LUN/Namespace) com uma reserva de espaço reduzida com base no protocolo selecionado.
+

NOTE: A partir do ONTAP 9.16.1, os sistemas de storage ASA R2 oferecem suporte para até 12 nós por cluster.

.. Selecione o *nível de serviço de desempenho* para sistemas de storage ASA R2 com 12 nós SVM que seja um cluster heterogêneo. Essa opção não estará disponível se o SVM selecionado for um cluster homogêneo ou usar um usuário SVM.
+
'Any' é o valor de nível de serviço de desempenho padrão (PSL). Essa configuração cria a unidade de armazenamento usando o algoritmo de posicionamento balanceado do ONTAP. No entanto, você pode selecionar a opção desempenho ou extrema, conforme necessário.

.. Selecione *Use as opções de volume existente*, *Enable QoS* conforme necessário e forneça os detalhes.
+

NOTE: No tipo de armazenamento ASA r2, a criação ou seleção de volume não se aplica à criação de unidade de armazenamento (LUN/Namespace).  Portanto, essas opções não são mostradas.

+

NOTE: Não é possível usar o volume existente para criar um armazenamento de dados VMFS com protocolo NVMe/FC ou NVMe/TCP.  Crie um novo volume para o armazenamento de dados VMFS.



. Revise os detalhes do datastore no painel *Summary* e selecione *Finish*.



NOTE: Se você criar o datastore em um cluster protegido, verá uma mensagem somente leitura: "O datastore está sendo montado em um cluster protegido."

.Resultado
As ferramentas ONTAP criam o armazenamento de dados VMFS e o montam em todos os hosts.

--
====