---
permalink: configure/discover-storage-systems-and-hosts.html 
sidebar: sidebar 
keywords:  
summary: Quando você executa pela primeira vez as ferramentas do ONTAP para VMware vSphere em um cliente vSphere, as ferramentas do ONTAP para VMware vSphere descobrem os hosts ESXi, suas exportações de LUNs e NFS, e os sistemas de storage NetApp que possuem esses LUNs e exportações. 
---
= Descubra sistemas de storage e hosts
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando as ONTAP tools for VMware vSphere são iniciadas no vSphere Client pela primeira vez, elas descobrem automaticamente os hosts ESXi, seus LUNs e exportações NFS associados, bem como os sistemas de armazenamento NetApp que possuem esses recursos.

.Antes de começar
* Certifique-se de que todos os hosts ESXi estejam ligados e conectados.
* Certifique-se de que todas as máquinas virtuais de armazenamento (SVMs) a serem descobertas estejam em execução e que cada nó do cluster tenha pelo menos uma LIF de dados configurada para o protocolo de armazenamento em uso (NFS ou iSCSI).


.Sobre esta tarefa
Você pode descobrir novos sistemas de armazenamento ou atualizar os existentes para obter os detalhes mais recentes sobre capacidade e configuração.  Você também pode alterar as ONTAP tools for VMware vSphere para acesso ao sistema de armazenamento.

Ao descobrir os sistemas de armazenamento, as ferramentas do ONTAP para VMware vSphere coletam informações dos hosts ESXi gerenciados pela instância do vCenter Server.

.Passos
. Na página inicial do vSphere Client, selecione *hosts and clusters*.
. Clique com o botão direito do mouse no data center desejado e selecione * Ferramentas NetApp ONTAP * > *Atualizar dados do host*.
+
Na caixa de diálogo *Confirm* (confirmar), confirme a sua escolha.

. Selecione os controladores de armazenamento descobertos que têm o status `Authentication Failure` e selecione *ações* > *Modificar*.
. Preencha as informações necessárias na caixa de diálogo *Modificar sistema de armazenamento*.
. Repita as etapas 4 e 5 para todos os controladores de armazenamento com `Authentication Failure` status.


Depois que o processo de descoberta estiver concluído, execute as seguintes ações:

* Use as ferramentas do ONTAP para VMware vSphere para configurar as configurações do host ESXi para hosts que exibem o ícone de alerta na coluna Configurações do adaptador, na coluna Configurações do MPIO ou na coluna Configurações de NFS.
* Forneça as credenciais do sistema de storage.

