---
permalink: configure/esxi-host-values.html 
sidebar: sidebar 
keywords:  
summary: Você pode definir tempos limite e outros valores nos hosts ESXi usando as ferramentas do ONTAP para VMware vSphere para garantir o melhor desempenho e o failover bem-sucedido. Os valores que as ferramentas do ONTAP para VMware vSphere definem são baseados no teste interno do NetApp. 
---
= Defina os valores do host ESXi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode definir tempos limite e outros valores nos hosts ESXi usando as ferramentas do ONTAP para VMware vSphere para garantir o melhor desempenho e o failover bem-sucedido. Os valores que as ferramentas do ONTAP para VMware vSphere definem são baseados no teste interno do NetApp.

Você pode definir os seguintes valores em um host ESXi:



== Definições do adaptador HBA/CNA

Define as definições de tempo limite de HBA recomendadas para sistemas de armazenamento NetApp.

|===
| Parâmetros | Defina este valor para... 


| Disk.QFullSampleSize | 32 para todas as configurações. Definir este valor ajuda a evitar erros de e/S. 


| Disk.QFullThreshold | 8 para todas as configurações. Definir este valor ajuda a evitar erros de e/S. 


| Tempos limite Emulex FC HBA | Valor padrão. 


| Tempos limite do QLogic FC HBA | Valor padrão. 
|===


== Definições MPIO

Configurações MPIO definem caminhos preferidos para sistemas de armazenamento NetApp. As configurações do MPIO determinam quais dos caminhos disponíveis são otimizados (em vez de caminhos não otimizados que atravessam o cabo de interconexão) e definem o caminho preferido para um desses caminhos.

Em ambientes de alto desempenho, ou quando você estiver testando o desempenho com um único armazenamento de dados LUN, considere alterar a configuração de balanceamento de carga da política de seleção de caminho (PSP) de round-robin (VMW_PSP_RR) da configuração padrão de IOPS de 1000 para um valor de 1.



== Definições NFS

|===


| Parâmetro | Defina este valor para... 


| NET.TcpipHeapSize | 32 


| NET.TcpipHeapMax | 1024 MB 


| NFS.MaxVolumes | 256 


| NFS41.MaxVolumes | 256 


| NFS.MaxQueueDepth | 128 ou superior 


| NFS.HeartbeatMaxFailures | 10 


| Frequência NFS.HeartbeatFrequency | 12 


| NFS.HeartbeatTimeout | 5 
|===