---
permalink: configure/install-nfs-vaai-plug-in.html 
sidebar: sidebar 
keywords:  
summary: 'Você pode instalar o plug-in NetApp NFS para VMware vStorage APIs para integração de array (VAAI) usando as ferramentas do ONTAP para VMware vSphere.' 
---
= Instale o plug-in NFS VAAI usando ferramentas ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O plug-in NFS vStorage API for Array Integration (NFS VAAI) conecta o VMware vSphere aos arrays de armazenamento NFS.  Use as ONTAP tools for VMware vSphere para instalar o plug-in VAAI. Isso permite que o conjunto de armazenamento NFS lide com determinadas operações de armazenamento em vez dos hosts ESXi.

.Antes de começar
* Baixe o https://mysupport.netapp.com/site/products/all/details/nfsplugin-vmware-vaai/downloads-tab["Plug-in NFS do NetApp para VMware VAAI"] pacote de instalação.
* Certifique-se de ter hosts ESXi com vSphere 7.0 U3 (patch mais recente ou posterior) e ONTAP 9.14.1 ou posterior.
* Montar um armazenamento de dados NFS.


.Passos
. Faça login no cliente vSphere.
. Selecione *Atalhos* > *Ferramentas do NetApp ONTAP* na seção plug-ins.
. Selecione *Settings* > *NFS VAAI Tools*.
. Se você já tiver carregado o plug-in VAAI no vCenter Server, selecione *Alterar* em *Versão existente*.  Caso ainda não tenha feito isso, selecione *Upload*.
. Navegue e selecione o `.vib` arquivo e selecione *Upload* para carregar o arquivo para as ferramentas do ONTAP.
. Selecione *Instalar no host ESXi*, selecione o host ESXi no qual deseja instalar o plug-in NFS VAAI e, em seguida, selecione *Instalar*.
+
O vSphere Web Client mostra apenas os hosts ESXi que podem instalar o plug-in. Você pode monitorar o progresso da instalação na seção de tarefas recentes.

. Reinicie o host ESXi manualmente após a instalação.
+
Após reiniciar o host ESXi, ONTAP tools for VMware vSphere detecta e habilita automaticamente o plug-in NFS VAAI.



.O que se segue?
Depois de instalar o plug-in NFS VAAI e reiniciar seu host ESXi, configure as políticas de exportação NFS para descarregamento de cópias VAAI.  Garantir que as regras da política de exportação atendam a estes requisitos:

* O volume ONTAP relevante permite chamadas NFSv4.
* O usuário root permanece como root e o NFSv4 é permitido em todos os volumes pai de junção.
* A opção de suporte VAAI é definida no servidor NFS relevante.


Para mais informações, consulte https://kb.netapp.com/on-prem/ontap/DM/VAAI/VAAI-KBs/Configure_the_correct_NFS_export_policies_for_VAAI_copy_offload["Configurar as políticas de exportação de NFS corretas para descarga de cópia VAAI"] Artigo da KB.

.Informações relacionadas
https://docs.netapp.com/us-en/ontap/nfs-admin/support-vmware-vstorage-over-nfs-concept.html["Suporte para VMware vStorage sobre NFS"]

https://docs.netapp.com/us-en/ontap/nfs-admin/enable-disable-nfsv40-task.html["Ativar ou desativar NFSv4,0"]

https://docs.netapp.com/us-en/ontap/nfs-admin/ontap-support-nfsv42-concept.html#nfs-v4-2-security-labels["Suporte ONTAP para NFSv4,2"]
