---
permalink: configure/protect-cluster.html 
sidebar: sidebar 
keywords: vVols datastore,delete vVol 
summary: As ferramentas do ONTAP para o VMware vSphere gerenciam a proteção dos clusters de host. 
---
= Proteger usando a proteção do cluster de host
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
As ferramentas do ONTAP para o VMware vSphere gerenciam a proteção dos clusters de host. Todos os armazenamentos de dados pertencentes ao SVM selecionado e montados em um ou mais hosts do cluster são protegidos em um cluster de host.

.Antes de começar
Certifique-se de atender a estes requisitos antes de proteger um cluster de host:

* O cluster host contém apenas armazenamentos de dados de uma única SVM.
* Os armazenamentos de dados no cluster do host não são montados em hosts fora do cluster.
* Os datastores montados no cluster do host são datastores VMFS com protocolo iSCSI ou FC.  Você não pode usar datastores vVols, NFS ou VMFS com protocolos NVMe/FC e NVMe/TCP.
* Os armazenamentos de dados baseados em volumes FlexVol/LUN montados em um host não fazem parte de nenhum grupo de consistência.
* Os armazenamentos de dados baseados em volumes FlexVol/LUN montados em um host não fazem parte de nenhum relacionamento do SnapMirror .
* O cluster host contém pelo menos um armazenamento de dados.


.Passos
. Faça login no cliente vSphere.
. Clique com o botão direito do mouse em um cluster de host e selecione * Ferramentas NetApp ONTAP * > *Proteger Cluster*.
. Na janela Proteger cluster, o sistema preenche automaticamente o tipo de armazenamento de dados e os detalhes da máquina virtual (VM) de armazenamento de origem.  Selecione o link dos armazenamentos de dados para visualizar os armazenamentos de dados protegidos.
. Selecione *Adicionar relacionamento*.
. Na janela *Add SnapMirror Relationship*, selecione *Target storage VM* e o tipo *Policy*.
+
O tipo de política pode ser assíncrono ou AutomatedFailOverDuplex.

+
Quando você adiciona a relação do SnapMirror como uma política de tipo AutomatedFailOverDuplex, você deve adicionar a VM de armazenamento de destino como back-end de armazenamento ao mesmo vCenter onde as ferramentas do ONTAP para VMware vSphere são implantadas.

+
No tipo de política AutomatedFailOverDuplex, há configurações de host uniformes e não uniformes.  Quando você seleciona o botão de alternância *configuração uniforme do host*, a configuração do grupo iniciador do host é replicada implicitamente no site de destino. Para mais informações, consulte link:../concepts/ontap-tools-concepts-terms.html["Principais conceitos e termos"] .

. Se você optar por ter uma configuração de host não uniforme, selecione o acesso do host (origem/destino) para cada host dentro desse cluster.
. Selecione *Adicionar*.
. Você pode editar a proteção do cluster do host usando a operação *Modificar proteção do cluster do host*.  Você pode editar ou excluir os relacionamentos usando as opções do menu de reticências.
. Selecione o botão *Protect*.
+
O sistema cria uma tarefa do vCenter com detalhes do ID do trabalho e mostra seu progresso no painel de tarefas recentes.  Esta é uma tarefa assíncrona; a interface do usuário mostra apenas o status de envio da solicitação e não espera a conclusão da tarefa.

. Para visualizar os clusters de host protegidos, acesse * Ferramentas NetApp ONTAP * > * Proteção * > * Relacionamentos de cluster de host *.  Selecione um grupo de consistência para visualizar sua capacidade, armazenamentos de dados associados e grupos de consistência filhos.


[NOTE]
====
Se você precisar remover a proteção dentro de uma hora após a criação, execute a descoberta de armazenamento primeiro.

====
.Informações relacionadas
https://www.vmware.com/docs/vmware-vsphere-metro-storage-cluster-vmsc["Cluster de armazenamento VMware vSphere Metro (vMSC)"^]
