---
permalink: configure/registration-process.html 
sidebar: sidebar 
keywords:  
summary: Você pode Registrar o provedor VASA com uma instância do vCenter Server usando as ferramentas do ONTAP para a interface de plug-in remota do VMware vSphere. 
---
= Registre o provedor VASA com uma instância do vCenter Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode Registrar o provedor VASA com uma instância do vCenter Server usando as ferramentas do ONTAP para VMware vSphere. A seção Configurações do provedor VASA exibe o status de Registro do provedor VASA para o vCenter Server selecionado.

.Passos
. Faça login no cliente vSphere.
. Selecione *Atalhos* > *Ferramentas do NetApp ONTAP* na seção plug-ins.
. Selecione *Definições* > *Definições do fornecedor VASA*. O estado de registo do fornecedor VASA será apresentado como não registado.
. Selecione o botão *Register* para registar o Fornecedor VASA.
. Introduza um nome e credenciais para o Fornecedor VASA. O nome de usuário só pode conter letras, números e sublinhados. O comprimento da palavra-passe deve ter entre 8 e 256 carateres.
. Selecione *Registe-se*.
. Depois de um registo e atualização de página bem-sucedidos, o estado, o nome e a versão do fornecedor VASA registado são apresentados. Após o registo, a ação de cancelamento de registo é ativada.


.O que vem a seguir
Verifique se o provedor VASA integrado está listado no provedor VASA do cliente vCenter:

.Passos
. Navegue até a instância do vCenter Server.
. Inicie sessão com as credenciais de administrador.
. Selecione *fornecedores de armazenamento* > *Configurar*. Verifique se o provedor VASA integrado está listado corretamente.

