---
permalink: release-notes/release-notes.html 
sidebar: sidebar 
keywords: release notes, ONTAP tools for VMware vSphere, 10.6 
summary: Consulte as notas de versão do ONTAP tools for VMware vSphere 10.6 para obter informações sobre recursos, compatibilidade e caminhos de migração suportados. 
---
= Notas de versão do ONTAP tools for VMware vSphere 10.6
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Consulte esta página para obter informações importantes sobre ONTAP tools for VMware vSphere 10.6 e, em seguida, acesse os tópicos relacionados para obter detalhes sobre recursos, compatibilidade e informações sobre migração.

Para obter uma lista completa dos novos recursos e melhorias, consulte xref:whats-new.adoc[Novidades no ONTAP tools for VMware vSphere 10.6].

Para obter as informações de compatibilidade mais atualizadas, consulte  https://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade do NetApp"^].

A migração é suportada das ONTAP tools for VMware vSphere versões 9.12D1, 9.13D2 e 9.13P2 para ONTAP tools for VMware vSphere 10.6.

Para obter mais informações, consulte o  https://library.netapp.com/ecm/ecm_download_file/ECMLP3383264["Notas de versão do ONTAP tools for VMware vSphere 10.6"^]. Você precisa fazer login com sua conta NetApp ou criar uma conta para acessar este documento.
