---
permalink: release-notes/whats-new.html 
sidebar: sidebar 
keywords: 'what"s new, release notes, 10.5, ONTAP tools for VMware vSphere' 
summary: Saiba mais sobre os novos recursos disponíveis nas ONTAP tools for VMware vSphere 10.5. 
---
= Novidades nas ONTAP tools for VMware vSphere 10.5
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Saiba mais sobre os novos recursos disponíveis nas ONTAP tools for VMware vSphere 10.5.

* *Qualificação da plataforma*


As ONTAP tools for VMware vSphere 10.5 adicionam suporte para sistemas ASA r2, fornecendo compatibilidade com as configurações mais recentes de hardware e software.  Esta versão também inclui integração com o ONTAP 9.16.1 e 9.17.1, expandindo os ambientes suportados.

* *Qualificação e certificações VMware*


As ONTAP tools for VMware vSphere 10.5 estão em conformidade com os padrões atuais de certificação de interoperabilidade da VMware, oferecendo suporte ao host ESXi e ao vCenter Server.

* * Suporte MetroCluster *


Esta versão apresenta suporte para configurações do MetroCluster , aprimorando recursos de alta disponibilidade e recuperação de desastres.

* *Gerenciamento de segurança e certificados*


Esta versão apresenta o gerenciamento simplificado de certificados autoassinados, melhorando a experiência do usuário e a adesão aos padrões de segurança.  Ele fornece fluxos de trabalho de validação de certificados aprimorados para proteger o ONTAP e as ONTAP tools for VMware vSphere .

* *Melhorias na replicação*


Esta versão oferece suporte à replicação VMFS com grupo de consistência hierárquica, incluindo sincronização ativa SRA e SnapMirror em sistemas ASA r2.  Ele suporta backups de RPO zero para melhorar a proteção e recuperação de dados.

* *Atualização e migração*


O processo de atualização e migração de versões anteriores do ONTAP tools for VMware vSphere para o ONTAP tools for VMware vSphere 10.5 foi projetado para ser contínuo e eficiente, minimizando o tempo de inatividade e garantindo uma transição tranquila.



== Plataformas ONTAP e versões do vCenter Server suportadas

Para obter os detalhes mais recentes sobre compatibilidade de versões, consulte https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT["Ferramenta de Matriz de interoperabilidade do NetApp"^] .
