---
permalink: manage/attach-detach-disk.html 
sidebar: sidebar 
keywords:  
summary: Anexe um disco de dados a uma máquina virtual para expandir a capacidade de armazenamento. 
---
= Anexe ou separe um disco de dados de uma máquina virtual
:allow-uri-read: 
:icons: font
:imagesdir: ../media/




== Anexe um disco de dados a uma máquina virtual

Anexe um disco de dados a uma máquina virtual para expandir a capacidade de armazenamento.

.Passos
. Faça login no cliente vSphere.
. Clique com o botão direito do mouse em uma máquina virtual no inventário e selecione *Editar configurações*.
. Na guia *hardware Virtual*, selecione *disco rígido existente*.
. Selecione a máquina virtual onde o disco existe.
. Selecione o disco que deseja anexar e selecione *OK*


.Resultado
O disco rígido aparece na lista dispositivos de hardware virtual.



== Separe um disco de dados da máquina virtual

Você pode separar um disco de dados conetado a uma máquina virtual quando não for mais necessário. Quando você descola o disco da máquina virtual, ele não é excluído automaticamente; ele permanece no sistema de armazenamento ONTAP.

.Passos
. Faça login no cliente vSphere.
. Clique com o botão direito do mouse em uma máquina virtual no inventário e selecione *Editar configurações*.
. Mova o ponteiro sobre o disco e selecione *Remover*.
+

NOTE: O disco é removido da máquina virtual. Se outras máquinas virtuais compartilharem o disco, os arquivos do disco não serão excluídos.



.Informações relacionadas
https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-virtual-machine-administration-guide-7-0/configuring-virtual-machine-hardwarevm-admin/virtual-disk-configurationvm-admin/add-a-hard-disk-to-a-virtual-machinevm-admin/add-a-new-hard-disk-to-a-virtual-machinevm-admin.html["Adicione um novo disco rígido a uma máquina virtual"]

https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-virtual-machine-administration-guide-7-0/configuring-virtual-machine-hardwarevm-admin/virtual-disk-configurationvm-admin/add-a-hard-disk-to-a-virtual-machinevm-admin/add-an-existing-hard-disk-to-a-virtual-machinevm-admin.html["Adicione um disco rígido existente a uma máquina virtual"]
