---
permalink: manage/certificate-manage.html 
sidebar: sidebar 
keywords: ONTAP tools certificates, VASA provider certificate, vCenter certificate trust, manage appliance certificates 
summary: Gerencie as ferramentas ONTAP e os certificados do VASA Provider, renove os certificados padrão ou substitua-os por certificados de CA personalizados. 
---
= Gerenciar certificados das ferramentas ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um certificado autoassinado é gerado por padrão para as ferramentas ONTAP e o provedor VASA durante a implantação. Você pode usar a interface do Gerenciador de ferramentas do ONTAP para renovar este certificado ou substituí-lo por um certificado de CA personalizado. Em implementações com vários vCenters, é necessário usar certificados de CA personalizados.


WARNING: Se os certificados expirarem sem renovação em tempo hábil, ONTAP tools para de funcionar. Renove os certificados antes do vencimento para manter a operação contínua e evitar interrupções no serviço.

.Antes de começar
Você deve ter o seguinte antes de começar:

* O nome de domínio mapeado para o endereço IP do ONTAP tools.
* Consulta nslookup bem-sucedida do nome de domínio, confirmando que ele resolve para o endereço IP correto.
* Certificados criados com o nome de domínio e o endereço IP das ferramentas ONTAP .



NOTE: Um endereço IP do ONTAP tools deve ser mapeado para um nome de domínio totalmente qualificado (FQDN). Os certificados devem conter o mesmo FQDN mapeado para o endereço IP do ONTAP tools no campo de assunto ou nos nomes alternativos de assunto.


NOTE: Não é possível alternar de um certificado assinado pela CA para um certificado autoassinado.

[role="tabbed-block"]
====
.Atualize o certificado das ferramentas do ONTAP
--
A guia Ferramentas do ONTAP mostra detalhes como tipo de certificado (autoassinado/CA assinado) e nome de domínio. Durante a implantação, o certificado autoassinado é gerado por padrão. Você pode renovar o certificado ou atualizar o certificado para CA.

.Passos
. Inicie o Gerenciador de ferramentas do ONTAP a partir de um navegador da Web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Faça login com as ferramentas do ONTAP para as credenciais de administrador do VMware vSphere fornecidas durante a implantação.
. Selecione *certificados* > *Ferramentas ONTAP* > *renovar* para renovar os certificados.
+
Você pode renovar o certificado se ele tiver expirado ou estiver próximo da data de expiração. A opção de renovação está disponível quando o tipo de certificado é autoassinado ou assinado por CA. Na janela pop-up, forneça os detalhes do certificado do servidor, da chave privada, da CA raiz e do certificado intermediário.

+

NOTE: O sistema estará offline até que o certificado seja renovado e você será desconetado da interface do Gerenciador de ferramentas do ONTAP.

. Para atualizar o certificado auto-assinado para certificado CA personalizado, selecione *certificados* > *Ferramentas ONTAP* > *Atualizar para CA* opção.
+
.. Na janela pop-up, carregue o certificado do servidor, a chave privada do certificado do servidor, o certificado da CA raiz e os ficheiros de certificado intermédios.
.. Insira o FQDN mapeado para o endereço IP do ONTAP (anteriormente IP do balanceador de carga) para o qual você gerou este certificado e atualize o certificado.
+

NOTE: O sistema estará offline até que a atualização esteja concluída, e você será desconetado da interface do Gerenciador de ferramentas do ONTAP.





--
.Atualize o certificado do fornecedor VASA
--
As ferramentas do ONTAP para o VMware vSphere são implantadas com um certificado autoassinado para o provedor VASA. Com isso, apenas uma instância do vCenter Server pode ser gerenciada para armazenamentos de dados vVols. Quando você gerencia várias instâncias do vCenter Server e deseja habilitar o recurso vVols nelas, você precisa alterar o certificado autoassinado para um certificado de CA personalizado.

.Passos
. Inicie o Gerenciador de ferramentas do ONTAP a partir de um navegador da Web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Faça login com as ferramentas do ONTAP para as credenciais de administrador do VMware vSphere fornecidas durante a implantação.
. Selecione *certificados* > *Fornecedor VASA* ou *Ferramentas ONTAP* > *renovar* para renovar os certificados.
. Selecione *certificados* > *Fornecedor VASA* ou *Ferramentas ONTAP* > *Upgrade para CA* para atualizar o certificado auto-assinado para certificado CA personalizado.
+
.. Na janela pop-up, carregue o certificado do servidor, a chave privada do certificado do servidor, o certificado da CA raiz e os ficheiros de certificado intermédios.
.. Insira o FQDN mapeado para o endereço IP do ONTAP (anteriormente IP do balanceador de carga) para o qual você gerou este certificado e atualize o certificado.
+

NOTE: O sistema estará offline até que a atualização esteja concluída, e você será desconetado da interface do Gerenciador de ferramentas do ONTAP.





--
.Atualizar o certificado dos serviços do ONTAP tools
--
A partir do ONTAP tools 10.5, a validade dos certificados mudou de 10 anos para 1 ano. A partir do ONTAP tools 10.5P2, durante a atualização do ONTAP tools, os certificados de comunicação de serviços internos são renovados automaticamente e o certificado autoassinado do gateway também é atualizado.

Use esta opção do console de manutenção para atualizar manualmente os certificados de comunicação de serviço internos quando você receber um alerta de que um certificado interno está perto de expirar ou se ONTAP tools não tiver sido atualizado em um ano. A partir do ONTAP tools 10.5P2, as atualizações renovam esses certificados automaticamente. Os certificados atualizados continuam com um período de validade de um ano (365 dias), o que ajuda a atender aos requisitos de auditoria.

.Passos
. Faça login no servidor vCenter.
. Localize a máquina virtual do ONTAP tools e inicie o console da web.
. Faça login usando as `maint` credenciais.
. Digitar `2` Para selecionar *Configuração do Sistema*.
. Digite  `9` para selecionar *Atualizar certificados de serviços do ONTAP tools*.



WARNING: Esta ação reinicia todos os serviços e pode causar indisponibilidade ou interrupção. Para continuar, confirme o aviso digitando  `y`, e então o processo de atualização será iniciado.

--
====