---
permalink: manage/change-valid-flag.html 
sidebar: sidebar 
keywords:  
summary: Você pode alterar o sinalizador de validação do certificado usando o console de manutenção. 
---
= Alterar sinalizador de validação de certificado
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Por padrão, o sinalizador de validação de certificado está habilitado (definido como verdadeiro).  Você pode definir o sinalizador de validação do certificado de backend de armazenamento ONTAP como falso se precisar ignorar as verificações do certificado SAN.  Esta configuração não é aplicável aos certificados do vCenter Server.

.Antes de começar
Você precisa ter credenciais de login de usuário de manutenção.

.Passos
. No vCenter Server, abra um console para as ferramentas do ONTAP.
. Inicie sessão como utilizador de manutenção.
. Digitar `1` para selecionar o Menu de configuração do aplicativo.
. Digitar `3` para alterar o sinalizador de validação do certificado.
+
O console de manutenção mostra o status do sinalizador de validação do certificado e solicita que você o altere.

. Digite 'y' para alternar o sinalizador ou 'n' para cancelar.


Ao ativar o sinalizador de validação de certificado (definido como verdadeiro), as ferramentas ONTAP verificam se todos os backends de armazenamento usam certificados com um Nome Alternativo do Assunto (SAN).  Se algum backend usar um certificado sem SAN, você não poderá ativar a validação de certificado.  Antes de ativar essa opção, verifique se todos os servidores de armazenamento utilizam certificados baseados em SAN.  Se você desativar o sinalizador de validação de certificado (definido como falso), as ferramentas ONTAP ignorarão a validação de certificado para todos os backends de armazenamento configurados.
