---
permalink: manage/configure-remote-diagnostic-access.html 
sidebar: sidebar 
keywords:  
summary: Você pode configurar as ferramentas do ONTAP para o VMware vSphere para habilitar o acesso SSH para o usuário diag. 
---
= Configure o acesso de diagnóstico remoto
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode configurar as ferramentas do ONTAP para o VMware vSphere para habilitar o acesso SSH para o usuário diag.

.Antes de começar
A extensão do provedor VASA deve estar habilitada para sua instância do vCenter Server.

*Sobre esta tarefa*

Usar SSH para acessar a conta de usuário diag tem as seguintes limitações:

* você tem permissão para apenas uma conta de login por ativação de SSH.
* O acesso SSH à conta de usuário diag é desativado quando uma das seguintes situações acontece:
+
** O tempo expira.
+
A sessão de início de sessão permanece válida apenas até à meia-noite do dia seguinte.

** Você faz login como um usuário diag novamente usando SSH.




.Passos
. No vCenter Server, abra um console para o provedor VASA.
. Inicie sessão como utilizador de manutenção.
. Digite `4` para selecionar *suporte e Diagnóstico*.
. Digitar `2` para selecionar *Habilitar acesso de diagnóstico remoto*.
. Introduza `y` na caixa de diálogo confirmação para ativar o acesso de diagnóstico remoto.
. Introduza uma palavra-passe para acesso remoto ao diagnóstico.

