---
permalink: manage/delete-ds.html 
sidebar: sidebar 
keywords: vVols datastore,delete vVol 
summary: A ação Excluir datastore exclui o datastore. No caso do armazenamento de dados NFS ou VMFS, uma caixa de diálogo aparece com a lista de VMs que estão usando o armazenamento de dados. 
---
= Excluir datastores
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esta seção descreve como excluir armazenamentos de dados NFS, VMFS ou vVols usando ferramentas ONTAP no vCenter Server.

Quando você exclui um armazenamento de dados, as seguintes ações são executadas dependendo do tipo de armazenamento de dados:

* O contêiner vVol está desmontado.
* Se o igroup não estiver em uso, iqn será removido do igroup.
* O contêiner vVol é excluído.
* Os volumes flexíveis são deixados no array de armazenamento.


Você pode excluir o armazenamento de dados somente se não houver vVols presentes no armazenamento de dados selecionado.

.Passos
. Faça login no cliente vSphere.
. Clique com o botão direito do mouse em um sistema host, um cluster de host ou um data center e selecione * Ferramentas NetApp ONTAP * > * Excluir armazenamento de dados *.
+

NOTE: Você não pode excluir um armazenamento de dados usado por máquinas virtuais.  Mova as máquinas virtuais para outro armazenamento de dados antes de excluí-las.  Não é possível excluir o volume se ele fizer parte de um cluster de host protegido.

+
.. No caso de um armazenamento de dados NFS ou VMFS, uma caixa de diálogo é exibida com a lista de VMs usando o armazenamento de dados.
.. Se nenhuma máquina virtual estiver associada a um armazenamento de dados VMFS, você verá uma caixa de diálogo de confirmação.  Se a proteção do cluster do host estiver habilitada e houver um relacionamento AFD, você poderá limpar elementos de armazenamento secundários.
.. Para armazenamentos de dados VMFS protegidos em sistemas ASA r2, certifique-se de que a proteção seja removida antes da exclusão.  A partir do ONTAP 9.17.1 e das ONTAP tools for VMware vSphere 10.5, você pode excluir um armazenamento de dados protegido.  Se for o único armazenamento de dados no grupo de proteção, a proteção do cluster do host será removida automaticamente.
.. Para armazenamentos de dados vVols , você pode excluir o armazenamento de dados somente se não houver vVols presentes.  A caixa de diálogo *Excluir armazenamento de dados* inclui uma opção para remover volumes do cluster ONTAP .
.. Para datastores vVols em sistemas ASA r2, não é possível excluir os volumes de suporte do ONTAP usando a opção *Excluir datastore*.


. Para excluir os volumes de backup no armazenamento ONTAP, selecione *Excluir volumes no cluster ONTAP*.
+

NOTE: Para armazenamentos de dados VMFS no armazenamento ONTAP unificado que fazem parte de um cluster de host protegido, não é possível excluir o volume do cluster ONTAP .



Quando você exclui um armazenamento de dados NFS, VMFS ou vVols , os igroups pais permanecem no sistema ONTAP .  Os igroups filho que não são mapeados para nenhum LUN são excluídos automaticamente.  As ferramentas ONTAP realizam uma limpeza diária para remover igroups pai padrão não mapeados.  Os igroups pai personalizados devem ser excluídos manualmente no ONTAP.  Todos os igroups pais restantes se tornam obsoletos e não podem ser reutilizados pelas ferramentas ONTAP .
