---
permalink: manage/disable-autosupport.html 
sidebar: sidebar 
keywords:  
summary: Ao configurar o sistema de armazenamento pela primeira vez, o AutoSupport é ativado por padrão. Ele envia mensagens para o suporte técnico 24 horas depois de ativado. 
---
= Desative o AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ao configurar o sistema de armazenamento pela primeira vez, o AutoSupport é ativado por padrão. Ele envia mensagens para o suporte técnico 24 horas depois de ativado. Ao desativar o AutoSupport, você não receberá mais suporte e monitoramento proativos.


NOTE: Recomenda-se que mantenha o AutoSupport ativado. Ele ajuda a acelerar a deteção e resolução de problemas. O sistema coleta informações do AutoSupport e as armazena localmente, mesmo quando desativado. No entanto, ele não envia o relatório para nenhuma rede.

.Passos
. Inicie o Gerenciador de ferramentas do ONTAP a partir de um navegador da Web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Faça login com as ferramentas do ONTAP para as credenciais de administrador do VMware vSphere fornecidas durante a implantação.
. Selecione a opção *Settings* > *Telemetry* > *Edit*.
. Desmarque a opção *AutoSupport* e salve as alterações.

