---
permalink: manage/edit-hostcluster-protection.html 
sidebar: sidebar 
keywords: vVols datastore,delete vVol 
summary: Você pode editar as relações SnapMirror do cluster de host protegido. Você pode adicionar, modificar e excluir as relações. No entanto, não é possível editar o nome do grupo de consistência. 
---
= Modificar cluster de host protegido
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode alterar as configurações de proteção de um cluster de host em um único fluxo de trabalho.  As seguintes alterações são suportadas:

* Adicione novos armazenamentos de dados ou hosts ao cluster protegido.
* Adicione novas relações SnapMirror às configurações de proteção.
* Exclua relacionamentos SnapMirror existentes das configurações de proteção.
* Modificar uma relação SnapMirror existente.



NOTE: Você precisa executar a descoberta de armazenamento depois de criar, editar ou excluir a proteção de um cluster de host para refletir as alterações.  Se você não executar a descoberta de armazenamento, as alterações serão refletidas depois que a descoberta periódica de armazenamento for acionada.



== Monitorar a proteção do cluster de host

Monitore o status de proteção, relacionamentos do SnapMirror , armazenamentos de dados e status do SnapMirror para cada cluster de host protegido.

.Passos
. Faça login no cliente vSphere.
. Acesse * Ferramentas NetApp ONTAP * > * Proteção * > * Relacionamentos de cluster de host *.
+
A coluna de proteção exibe um ícone que mostra o status da proteção.

. Passe o Mouse sobre o ícone para ver mais detalhes.




== Adicione novos armazenamentos de dados ou hosts

Adicione hosts ou crie armazenamentos de dados no cluster protegido usando a interface de usuário do vCenter.

.Passos
. Faça login no cliente vSphere.
. Para editar as propriedades de um cluster protegido, é possível
+
.. Acesse * Ferramentas NetApp ONTAP * > * Proteção * > * Relacionamentos de cluster de host *, selecione o menu de reticências ao lado do cluster e selecione * Editar * ou
.. Clique com o botão direito do mouse em um cluster de host e selecione * Ferramentas NetApp ONTAP * > *Proteger Cluster*.


. Se você criar um armazenamento de dados na interface do usuário do vCenter, ele aparecerá como desprotegido.  Você pode visualizar todos os armazenamentos de dados no cluster e seu status de proteção em uma caixa de diálogo.  Selecione o botão *Proteger* para habilitar a proteção.
+

NOTE: Depois de criar um armazenamento de dados na interface do usuário do vCenter Server, selecione *Descobrir* na página de visão geral para mostrar o armazenamento de dados como candidato à proteção no cluster do host.  O status da proteção é atualizado para protegido após a próxima descoberta de proteção periódica.

. Se você adicionar um novo host ESXi, o status de proteção será mostrado como parcialmente protegido.  Selecione o menu de reticências nas configurações do SnapMirror e selecione *Editar* para definir a proximidade do host ESXi recém-adicionado.
+

NOTE: Para relacionamentos assíncronos, a edição não é suportada em ferramentas ONTAP porque o SVM de destino para um site terciário não pode ser adicionado à mesma instância.  Para modificar a configuração do relacionamento, use o Gerenciador do Sistema ou a CLI no SVM de destino.

. Após fazer as alterações, selecione *Salvar*.
. Você pode ver as alterações na janela *Protect Cluster*.


As ferramentas ONTAP criam uma tarefa do vCenter, e você pode acompanhar seu progresso no painel *Tarefa recente*.



== Adicione uma nova relação do SnapMirror

.Passos
. Faça login no cliente vSphere.
. Para editar as propriedades de um cluster protegido, é possível
+
.. Acesse * Ferramentas NetApp ONTAP * > * Proteção * > * Relacionamentos de cluster de host *, selecione o menu de reticências no cluster e selecione * Editar * ou
.. Clique com o botão direito do mouse em um cluster de host e selecione * Ferramentas NetApp ONTAP * > *Proteger Cluster*.


. Selecione *Adicionar relacionamento*.
. Adicione um novo relacionamento como tipo de política *assíncrono* ou *AutomatedFailOverDuplex*.
. Selecione *Protect*.
+
Você pode ver as alterações na janela *Protect Cluster*.



As ferramentas ONTAP criam uma tarefa do vCenter, e você pode acompanhar seu progresso no painel *Tarefa recente*.



== Eliminar uma relação SnapMirror existente

Para excluir um relacionamento assíncrono do SnapMirror , certifique-se de que o SVM ou cluster do site secundário seja adicionado como um backend de armazenamento nas ONTAP tools for VMware vSphere.  Não é possível excluir todos os relacionamentos do SnapMirror de uma só vez.  A exclusão de um relacionamento também remove o relacionamento correspondente do cluster ONTAP .  Quando você exclui um relacionamento Automated Failover Duplex SnapMirror , o sistema desmapeia os armazenamentos de dados de destino e exclui o grupo de consistência, LUNs, volumes e igroups do cluster ONTAP de destino.

Quando você exclui o relacionamento, o sistema verifica novamente o site secundário para remover o LUN não mapeado como um caminho ativo dos hosts.

.Passos
. Faça login no cliente vSphere.
. Para editar as propriedades de um cluster protegido, é possível
+
.. Acesse * Ferramentas NetApp ONTAP * > * Proteção * > * Relacionamentos de cluster de host *, selecione o menu de reticências no cluster e selecione * Editar * ou
.. Clique com o botão direito do mouse em um cluster de host e selecione * Ferramentas NetApp ONTAP * > *Proteger Cluster*.


. Selecione o menu de elipse nas configurações do SnapMirror e selecione *Excluir*.
+
** Se você excluir um relacionamento baseado em tipo de política assíncrona de um cluster de host protegido, deverá remover manualmente os elementos de armazenamento do cluster de armazenamento terciário.  Os elementos de armazenamento incluem grupos de consistência, volumes (para sistemas ONTAP ), unidades de armazenamento (LUNs/Namespaces) e snapshots.
** Se você excluir um relacionamento baseado em política de Failover Duplex Automatizado (AFD) de um cluster de host protegido, poderá optar por remover os elementos de armazenamento associados no armazenamento secundário diretamente da interface.
** Se você excluir um relacionamento baseado em política de Failover Duplex Automatizado (AFD) e o grupo de consistência agora for hierárquico para backups em nível de aplicativo, um aviso será exibido sobre o impacto do backup.  Confirme para prosseguir.  Após a confirmação, exclua os elementos de armazenamento associados no armazenamento secundário.  Se você não removê-los, eles permanecerão no site secundário.




As ferramentas ONTAP criam uma tarefa do vCenter, e você pode acompanhar seu progresso no painel *Tarefa recente*.



== Modificar uma relação SnapMirror existente

Para modificar um relacionamento assíncrono do SnapMirror , certifique-se de que o SVM ou cluster do site secundário seja adicionado como um backend de armazenamento nas ONTAP tools for VMware vSphere.  Para relacionamentos SnapMirror de Failover Duplex Automatizado, você pode atualizar a proximidade do host para configurações uniformes ou o acesso ao host para configurações não uniformes.  Não há suporte para a alternância entre os tipos de política de failover duplex assíncrono e automatizado.  Você pode configurar as configurações de proximidade ou acesso para hosts recém-descobertos no cluster.


NOTE: Não é possível editar um relacionamento assíncrono SnapMirror existente.

.Passos
. Faça login no cliente vSphere.
. Para editar as propriedades de um cluster protegido, é possível
+
.. Acesse * Ferramentas NetApp ONTAP * > * Proteção * > * Relacionamentos de cluster de host *, selecione o menu de reticências no cluster e selecione * Editar * ou
.. Clique com o botão direito do mouse em um cluster de host e selecione * Ferramentas NetApp ONTAP * > *Proteger Cluster*.


. Se o tipo de política AutomatedFailOverDuplex for selecionado, adicione detalhes de proximidade ou acesso ao host.
. Selecione o botão *Protect*.


As ferramentas ONTAP criam uma tarefa do vCenter.  Acompanhe seu progresso no painel *Tarefa recente*.
