---
permalink: manage/enable-services.html 
sidebar: sidebar 
keywords:  
summary: 'Você pode alterar a senha do administrador usando o Gerenciador de ferramentas do ONTAP para habilitar serviços como o provedor VASA, a importação de configuração do vVols e a recuperação de desastres (SRA) usando o Gerenciador de ferramentas do ONTAP.' 
---
= Habilite as ferramentas do ONTAP para os serviços do VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode alterar a senha do administrador usando o Gerenciador de ferramentas do ONTAP para habilitar serviços como o provedor VASA, a importação de configuração do vVols e a recuperação de desastres (SRA) usando o Gerenciador de ferramentas do ONTAP.

.Passos
. Inicie o Gerenciador de ferramentas do ONTAP a partir de um navegador da Web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Faça login com as ferramentas do ONTAP para as credenciais de administrador do VMware vSphere fornecidas durante a implantação.
. Selecione *Edit Appliance Settings* (Editar definições do dispositivo) na secção Overview (Descrição geral).
. Na seção *Serviços*, você pode habilitar serviços opcionais como o provedor VASA, a importação de configuração vVols e a recuperação de desastres (SRA) de acordo com suas necessidades.
+
Ao ativar os serviços pela primeira vez, você deve criar as credenciais do provedor VASA e do SRA. Eles são usados para Registrar ou habilitar o provedor VASA e os serviços SRA no vCenter Server. O nome de usuário só pode conter letras, números e sublinhados. O comprimento da palavra-passe deve ter entre 8 e 256 carateres.

+

NOTE: Antes de desabilitar quaisquer serviços opcionais, certifique-se de que os servidores vCenter gerenciados pelas ferramentas ONTAP não os utilizem.

+
A opção *Permitir importação de configuração vVols * é exibida somente quando o serviço VASA Provider está habilitado.  Esta opção permite a migração de dados vVols do ONTAP Tools 9.xx para o ONTAP Tools 10.5.


