---
permalink: manage/enable-services.html 
sidebar: sidebar 
keywords: enable ONTAP tools services, enable VASA provider, enable SRA service, vVols service configuration 
summary: 'Habilite os serviços opcionais das ONTAP tools, incluindo VASA Provider, importação de configuração de vVols e recuperação de desastres (SRA).' 
---
= Habilitar os serviços do ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Use o Gerenciador de Ferramentas ONTAP para habilitar serviços opcionais, como o VASA Provider, a importação de configuração de vVols e a recuperação de desastres (SRA).

.Passos
. Inicie o Gerenciador de ferramentas do ONTAP a partir de um navegador da Web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Faça login com as ferramentas do ONTAP para as credenciais de administrador do VMware vSphere fornecidas durante a implantação.
. Na seção *Visão geral*, selecione *Editar configurações do appliance*.
. Na seção *Serviços*, habilite os serviços opcionais de que você precisa, como VASA Provider, importação de configuração vVols e recuperação de desastres (SRA).
+
Ao ativar esses serviços pela primeira vez, crie as credenciais do VASA Provider e do SRA.

+
** Utilize essas credenciais para registrar e habilitar os serviços VASA Provider e SRA no vCenter Server.
** O nome de usuário pode conter apenas letras, números e sublinhados.
** A senha deve ter entre 8 e 256 caracteres.





NOTE: Antes de desativar qualquer serviço opcional, certifique-se de que as instâncias do servidor vCenter gerenciadas pelas ONTAP tools não utilizem esse serviço.

A opção *Permitir importação de configuração de vVols* só aparece quando o serviço VASA Provider está ativado. Essa opção permite a migração de dados de vVols do ONTAP tools 9.x para o ONTAP tools 10.6.
