---
permalink: manage/manage-vcenter.html 
sidebar: sidebar 
keywords: manage vCenter instances, add remove vCenter, ONTAP tools vCenter credentials, vCenter certificate management 
summary: Gerencie instâncias do vCenter nas ONTAP tools para controlar hosts, máquinas virtuais e backends de storage. 
---
= Gerenciar instâncias do vCenter Server em ferramentas ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
As instâncias do vCenter Server são plataformas de gerenciamento central que permitem controlar hosts, máquinas virtuais e backends de armazenamento.



[[dissociate-storage-backends-from-a-vcenter-server-instance]]
== Desvincular backends de storage de uma instância do servidor vCenter

A página de listagem do vCenter Server mostra o número associado de backends de armazenamento. Cada instância do vCenter Server tem a opção de associar ou desassociar a um back-end de armazenamento.

.Passos
. Inicie o Gerenciador de ferramentas do ONTAP a partir de um navegador da Web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Faça login com as ferramentas do ONTAP para as credenciais de administrador do VMware vSphere fornecidas durante a implantação.
. Selecione *vCenters* na barra lateral.
. Selecione as reticências verticais para o vCenter Server que você deseja associar ou desassociar com backends de storage.
. Selecione *dissociar o back-end de armazenamento*.




[[modify-a-vcenter-server-instance]]
== Modifique uma instância do vCenter Server

. Inicie o Gerenciador de ferramentas do ONTAP a partir de um navegador da Web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Faça login com as ferramentas do ONTAP para as credenciais de administrador do VMware vSphere fornecidas durante a implantação.
. Selecione *vCenters* na barra lateral.
. Selecione as reticências verticais para o vCenter Server que você deseja modificar e selecione *Modificar*.
. Na janela *Modificar vCenter*, insira o nome de usuário, a senha e os detalhes da porta.
. Carregue o certificado e selecione *Modificar*.




[[remove-a-vcenter-server-instance]]
== Remova uma instância do vCenter Server

Você pode remover uma instância do servidor vCenter mesmo quando datastores e backends de storage ainda estão associados. A caixa de diálogo *Remove vCenter* orienta você pelas ações necessárias com base no estado atual do servidor vCenter.


NOTE: A exclusão forçada remove apenas os metadados das ONTAP tools. Ela não remove objetos de storage ONTAP (volumes ou LUNs), datastores do vSphere ou máquinas virtuais.

.Antes de começar
A exclusão forçada está bloqueada se o vCenter Server tiver datastores vVols ou datastores protegidos. Antes de prosseguir:

* Remova ou migre todos os datastores vVols.
* Desproteja todos os datastores protegidos.
* Certifique-se de que nenhuma tarefa de descoberta esteja em execução. A operação de exclusão forçada não prosseguirá se houver tarefas de descoberta em andamento.



NOTE: Os backends de storage globais compartilhados com outras instâncias do vCenter Server são mantidos. Somente a associação com o vCenter Server excluído é removida.

.Passos
. Inicie o Gerenciador de ferramentas do ONTAP a partir de um navegador da Web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Faça login com as ferramentas do ONTAP para as credenciais de administrador do VMware vSphere fornecidas durante a implantação.
. Selecione *vCenters* na barra lateral.
. Selecione as reticências verticais para o vCenter Server desejado e selecione *Remover*.
. Na caixa de diálogo *Remover vCenter*, revise o estado do servidor vCenter e conclua as ações necessárias.
+
O comportamento do diálogo depende do estado do vCenter Server:

+
[cols="2,2,3"]
|===
| Condição | Comportamento de diálogo | Ação necessária 


| Sem vVols ou armazenamentos de dados protegidos, mas os backends de storage estão associados | A caixa de diálogo exibe o número de storage backends e datastores associados. | Selecione *Remover todos os artefatos de storage deste vCenter Server* e *Entendo que os datastores associados não serão mais gerenciados por ONTAP tools*. 


| Sem datastores vVols, datastores protegidos ou storage backends | A caixa de diálogo confirma a remoção. | Nenhuma ação adicional é necessária. 
|===
. Selecione *Forçar exclusão*.
. Confirme a ação.


.Resultado
As ferramentas ONTAP executam as seguintes ações automaticamente:

* O plug-in não está registado.
* As funções plug-in Privileges e plug-in são removidas.


A instância do servidor vCenter não é mais gerenciada pelas ONTAP tools.

Se o servidor vCenter estiver inacessível durante a exclusão:

* As ferramentas ONTAP removem o registro do servidor vCenter.
* O cancelamento do registro do plug-in não ocorre.
* Uma mensagem de aviso é exibida.
* Você deve cancelar o registro do plug-in manualmente no VMware vCenter Server.




[[renew-vcenter-server-certificate]]
== Renovar certificado do vCenter Server

As ferramentas ONTAP notificam você quando o certificado do vCenter está perto de expirar ou já expirou. Após renovar o certificado do vCenter, carregue o novo certificado nas ferramentas do ONTAP seguindo os passos abaixo:

. Faça login no shell de diagnóstico remoto das ferramentas ONTAP .
. Obtenha o certificado vCenter renovado no shell de diagnóstico:
+
[listing]
----
echo | openssl s_client connect <vcenter>:443 2>&1 | sed -n '/-BEGIN CERTIFICATE/,/END CERTIFICATE/p'
----
. Certifique-se de que o certificado esteja no formato ASCII Base 64 e inclua as linhas inicial e final, por exemplo:
+
[listing]
----
---{}BEGIN CERTIFICATE{}---
MIIFUzCCA7ugAwIBAgIJANOgLapcl5oSMA0GCSqGSIb3DQEBCwUAMIGJMQwwCgYD
VQQDDAN2YzExFDASBgoJkiaJk/IsZAEZFgRkZW1vMRUwEwYKCZImiZPyLGQBGRYF
bG9jYWwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRwwGgYDVQQK
DBN2YzEuZGVtby5uZXRhcHAuY29tMQwwCgYDVQQLDANMT0QwHhcNMjQwNDA1MTgw
NTE4WhcNMjYwNDA1MTgwNTE4WjBzMRwwGgYDVQQDDBN2YzEuZGVtby5uZXRhcHAu
Y29tMQswCQYDVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTESMBAGA1UEBwwJ
UGFsbyBBbHRvMQ8wDQYDVQQKDAZOZXRBcHAxDDAKBgNVBAsMA0xPRDCCAaIwDQYJ
KoZIhvcNAQEBBQADggGPADCCAYoCggGBALU8OCWMtA2gvIC/OTw/7xucvPVuM+b8
DhzvNpQ2phjfr6ctEhbntPpqPdu+t2CKK7l0mzg3D9cJ/rvMvdDDXr0tgaD1oi2u
ZDW0CaF0QhLOpNfRXMoogBZ66csEhViAy3CHTcOse770mA/PyoHgrCPZngVlZIiQ
TIWpdQMbEEzFIkrLfC70UW2MzfublrsH7Dn/kOu/iCSlVJWixKf7SmZtVQ5ZxBTD
UlJSiqoX1eRXGyunArEvrIpOY9kkKXUElm3hGnk/ZmiuBJ+HqUYqYW+H+7vE3lKa
6NEqDX+tZotxTx2bXMjeiIWU30ZbshgeXlIG9qc49clBoC9iGjavhctOcaXg/W3h
dLKK5ds3rpRERgMg6VMkrfiqAJuiq+b3sTvXMAul/3hL7hz5QABAE/hP4ZvIHV02
WWDQRLiuVFAcDAyvCrO9Irx0Gk1RyRShKYakdWxZ3hhMdLuGq0yvRXqo1Ib94zwO
JfBJHjFToA/GqwromZgiTzJkKq5xbN8MFwIDAQABo4HSMIHPMAsGA1UdDwQEAwIF
4DA7BgNVHREENDAygRVlbWFpbEBkZW1vLm5ldGFwcC5jb22HBMCoAB+CE3ZjMS5k
ZW1vLm5ldGFwcC5jb20wHQYDVR0OBBYEFJ0V0zY+JRpFrEt31ovAY4BLFXmAMB8G
A1UdIwQYMBaAFENf6fRxWF3OJQNTPIdUpK6kjA78MEMGCCsGAQUFBwEBBDcwNTAz
BggrBgEFBQcwAoYnaHR0cHM6Ly92YzEuZGVtby5uZXRhcHAuY29tL2FmZC92ZWNz
L2NhMA0GCSqGSIb3DQEBCwUAA4IBgQBaDfk7GBM4vmhzYCqGrr6KB+h3qeTJ+Y0Y
5nIPRP1HucawDQ8QTay605ddJ8gFGoxkOQDn9tdXWXGjnTRFOT8R+Hw/nUfVSiDP
sYienb16copzUNwtqh+m9Ifow74Gf+ulRzEC0EAVO1X/nTEYH6NKM6Wy7y7F8g5J
lrpM3JY90ZChMqHO3Av/88rbErfQ/gU1brJ3u9Gks4e20Z7Ff312ZKhWRuJDlN2Z
0tc/gp90N9GxaVvELovq/pdjaZ8xiXCxa6piicrJd9WnqMH1gmxP2PIBDxMDBWBG
gwsfs5H7VG9MJYks6lViNsGclo0EwEdF0MfoB3JtsWpPWq6+jBua0Jm7/aFCU+Ht
mykr0gaV7muegoiBQuDma4EkAI31D7ZlUgJQaw157NTk4RW3TFcbtViBHJkM54Hr
iVm0cl+2BZNi/QTMh/MkWV2dYXJ3NuNlqqfzFY+bUfkzkR4SneMk0HX3joNNYDJv
siO7bL+k/Pxql27NVIhuCoVJAlcI7ak=
---{}END CERTIFICATE{}---
----
. Copie a saída e salve-a como um arquivo de texto com um `.pem` extensão na sua área de trabalho.
. Inicie o Gerenciador de ferramentas do ONTAP a partir de um navegador da Web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Faça login com as ferramentas do ONTAP para as credenciais de administrador do VMware vSphere fornecidas durante a implantação.
. Selecione a instância aplicável do vCenter Server na barra lateral
. Selecione as reticências verticais para o vCenter Server que você deseja modificar e selecione *Modificar*.
. Na janela *Modificar vCenter*, insira o nome de usuário, a senha e os detalhes da porta.
. Faça o upload do certificado e selecione *Modificar*.


.Informações relacionadas
link:../manage/configure-remote-diagnostic-access.html["Configure o acesso de diagnóstico remoto"]
