---
permalink: manage/migrate-virtual-machines.html 
sidebar: sidebar 
keywords:  
summary: Você deve estar ciente de algumas das considerações ao migrar máquinas virtuais existentes em seu data center. 
---
= Considerações para migrar ou clonar máquinas virtuais
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve estar ciente de algumas das considerações ao migrar máquinas virtuais existentes em seu data center.



== Migrar máquinas virtuais protegidas

Você pode migrar as máquinas virtuais protegidas para:

* O mesmo datastore vVols em um host ESXi diferente
* Armazenamento de dados vVols compatível diferente no mesmo host ESXi
* Armazenamento de dados vVols compatível diferente em um host ESXi diferente


Se você migrar a máquina virtual para um FlexVol volume diferente, o sistema atualizará o arquivo de metadados desse volume com as informações da máquina virtual. Se uma máquina virtual for migrada para um host ESXi diferente, mas com o mesmo armazenamento, o arquivo de metadados do FlexVol volume subjacente não será modificado.



== Máquinas virtuais protegidas contra clones

Você pode clonar máquinas virtuais protegidas para o seguinte:

* Mesmo contêiner do mesmo FlexVol volume usando o grupo de replicação
+
O arquivo de metadados do mesmo FlexVol volume é atualizado com os detalhes da máquina virtual clonada.

* Mesmo contêiner de um FlexVol volume diferente usando o grupo de replicação
+
O FlexVol volume onde a máquina virtual clonada é colocada, o arquivo de metadados é atualizado com os detalhes da máquina virtual clonada.

* Datastore diferente de contêiner ou vVols
+
O FlexVol volume onde a máquina virtual clonada é colocada, o arquivo de metadados recebe detalhes atualizados da máquina virtual.



Atualmente, a VMware não oferece suporte a máquinas virtuais clonadas em um modelo de VM.

É suportado clone-of-Clone de uma máquina virtual protegida.

 https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-virtual-machine-administration-guide-7-0/deploying-virtual-machinesvm-admin/clone-an-existing-virtual-machine-h5vm-admin.html["Criando uma Máquina Virtual para Clonagem"]Consulte para obter mais detalhes.



== Instantâneos de máquina virtual

Atualmente, apenas instantâneos de máquina virtual sem memória são suportados. Se a máquina virtual tiver Snapshot com memória, a máquina virtual não será considerada para proteção.

Você também não pode proteger máquinas virtuais desprotegidas que tenham instantâneo de memória.  Para esta versão, espera-se que você exclua o instantâneo de memória antes de habilitar a proteção para a máquina virtual.

Para uma máquina virtual Windows com o tipo de armazenamento ASA r2, um snapshot da máquina virtual é somente leitura.  Ao ligar a máquina virtual, o provedor VASA cria um LUN a partir do snapshot somente leitura e habilita as IOPS.  Ao desligar a máquina virtual, o provedor VASA exclui o LUN e desativa as IOPS.
