---
permalink: manage/migrate-virtual-machines.html 
sidebar: sidebar 
keywords:  
summary: É importante estar ciente de algumas considerações ao migrar máquinas virtuais existentes em seu data center. 
---
= Considerações sobre migração e clonagem de máquinas virtuais para ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphere suportam todos os principais tipos de migração de máquina virtual, incluindo somente computação (vMotion), somente armazenamento (Storage vMotion) e migração combinada de computação e armazenamento em todos os datastores. Este tópico descreve as principais considerações e práticas recomendadas para garantir a migração e clonagem bem-sucedidas de máquinas virtuais, independentemente do tipo de datastore subjacente.



== Migrar máquinas virtuais protegidas

Você pode migrar máquinas virtuais protegidas para:

* O mesmo armazenamento de dados em um host ESXi diferente
* Um armazenamento de dados compatível diferente no mesmo host ESXi
* Um armazenamento de dados compatível diferente em um host ESXi diferente


Se você migrar a máquina virtual para um volume FlexVol diferente, o sistema atualizará o arquivo de metadados desse volume com as informações da máquina virtual. Se uma máquina virtual for migrada para um host ESXi diferente, mas para o mesmo storage, o arquivo de metadados do volume FlexVol subjacente não será modificado.

Para obter informações sobre a migração de máquinas virtuais, consulte a documentação da Broadcom: https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/9-0/vcenter-and-host-management/migrating-virtual-machines-host-management.html["vSphere Migração de Máquinas Virtuais"]



== Máquinas virtuais protegidas contra clones

Você pode clonar máquinas virtuais protegidas para o seguinte:

* O mesmo contêiner do mesmo FlexVol volume usando um grupo de replicação
+
O arquivo de metadados do mesmo volume FlexVol é atualizado com os detalhes da máquina virtual clonada.

* O mesmo contêiner de um volume FlexVol diferente usando um grupo de replicação
+
No volume FlexVol onde a máquina virtual clonada é colocada, o arquivo de metadados é atualizado com os detalhes da máquina virtual clonada.

* Um contêiner ou vVols datastore diferente
+
No volume FlexVol onde a máquina virtual clonada é colocada, o arquivo de metadados é atualizado com os detalhes da máquina virtual.



Atualmente, a VMware não oferece suporte a máquinas virtuais clonadas para um modelo de máquina virtual.

É possível criar um clone de um clone de uma máquina virtual protegida.

Consulte a documentação da Broadcom: https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-virtual-machine-administration-guide-7-0/deploying-virtual-machinesvm-admin/clone-an-existing-virtual-machine-h5vm-admin.html["Criando uma Máquina Virtual para Clonagem"] para obter mais detalhes.



== Instantâneos de máquinas virtuais

ONTAP tools suporta snapshots de máquinas virtuais por meio de fluxos de trabalho padrão da VMware. Snapshots são pontos de reversão de curto prazo destinados a casos de uso como testes e preparação de patches. Eles não substituem backup ou proteção de dados baseada em replicação. Executar uma máquina virtual em um snapshot por períodos prolongados pode causar instabilidade e perda de dados.

Você pode tirar snapshots consistentes com falhas (snapshots sem o estado da memória, que podem ser usados para reiniciar a máquina virtual em um estado consistente) em todos os tipos de datastore compatíveis. Snapshots quiesced, que usam o VMware Tools para gravar os dados em memória no disco antes da captura, também são compatíveis. Para obter uma visão geral dos tipos e comportamentos de snapshots, consulte  https://knowledge.broadcom.com/external/article/342618/overview-of-virtual-machine-snapshots-in.html["Visão geral dos snapshots de máquina virtual em vSphere"].


NOTE: Os snapshots de memória capturam o estado da memória em execução e interrompem temporariamente a máquina virtual. Eles não são suportados nos fluxos de trabalho das ONTAP tools. Se uma máquina virtual tiver um snapshot de memória, você deve excluí-lo antes que a máquina virtual possa ser incluída em um grupo de consistência ou em um relacionamento de cluster de hosts gerenciado pelas ONTAP tools.

Nos sistemas de storage ASA r2, o comportamento dos snapshots de máquina virtual difere de outros tipos de storage. Os snapshots são somente leitura. Ao ligar a máquina virtual, o VASA Provider cria um LUN a partir do snapshot somente leitura e habilita as IOPS. Ao desligar a máquina virtual, o VASA Provider exclui o LUN e desabilita as IOPS.

Para obter informações sobre como gerenciar snapshots de máquinas virtuais, consulte a documentação da Broadcom https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/9-0/vsphere-virtual-machine-administration/managing-virtual-machinesvsphere-vm-admin/using-snapshots-to-manage-virtual-machinesvsphere-vm-admin.html["Gerencie máquinas virtuais com snapshots"].
