---
permalink: manage/mount-datastores-on-host.html 
sidebar: sidebar 
keywords:  
summary: A montagem de um datastore fornece acesso ao storage a hosts adicionais. Você pode montar o datastore nos hosts adicionais depois de adicionar os hosts ao seu ambiente VMware. 
---
= Montar armazenamentos de dados NFS e VMFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A montagem de um datastore fornece acesso ao storage a hosts adicionais. Você pode montar o datastore nos hosts adicionais depois de adicionar os hosts ao seu ambiente VMware.


NOTE: Ao adicionar um novo host ESXi usando o https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/9-0/use-quickstart-to-add---host-to-a-cluster.html["Adicionar um host ESX ao seu fluxo de trabalho de cluster vSphere"] Aguarde a conclusão da descoberta de hosts agendada antes que ela apareça nas ferramentas do ONTAP . Alternativamente, você pode executar a descoberta manualmente a partir da tela de visão geral das ferramentas do NetApp ONTAP .

.Sobre esta tarefa
* Algumas ações com o botão direito do Mouse são desativadas ou indisponíveis dependendo da versão do cliente vSphere e do tipo de datastore selecionado.
+
** Se você estiver usando o vSphere Client 8,0 ou versões posteriores, algumas das opções de clique com o botão direito do Mouse ficam ocultas.
** Das versões vSphere 7.0U3 ao vSphere 8,0, mesmo que as opções apareçam, a ação será desativada.


* O vSphere desativa a opção de montagem do armazenamento de dados quando o cluster de hosts está protegido com configurações uniformes.


.Passos
. Na página inicial do vSphere Client, selecione *hosts and clusters*.
. No painel de navegação esquerdo, selecione os data centers que contêm os hosts.
. Para montar datastores NFS/VMFS em um host ou cluster de hosts, clique com o botão direito e selecione *Ferramentas NetApp ONTAP * > *Montar Datastores*.
. Selecione os armazenamentos de dados que você deseja montar e selecione *Mount*.


.O que se segue?
Você pode acompanhar o progresso no painel de tarefas recentes.

.Tópico relacionado
link:../manage/add-vsphere-host.html["Adicionar novos hosts VMware vSphere"]
