---
permalink: manage/mount-a-vvols-datastore.html 
sidebar: sidebar 
keywords: mount vVols datastore, add vVol datastore to hosts, ONTAP tools vVol host access, VMware virtual volumes mount 
summary: Monte um datastore vVols em hosts adicionais para fornecer acesso ao storage em todo o seu ambiente virtual. 
---
= Montar um datastore vVols nas ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode montar um datastore do VMware Virtual Volumes (vVols) em um ou mais hosts adicionais para fornecer acesso ao storage a hosts adicionais. Você pode desmontar um datastore vVols apenas por meio de APIs em nível de host. Desmontar datastore em nível de cluster não é suportado.


NOTE: Após adicionar o host, aguarde a conclusão da descoberta agendada antes que ele apareça nas ONTAP tools. Como alternativa, você pode executar a descoberta manualmente na tela de visão geral das NetApp ONTAP tools. Para obter informações sobre como adicionar um host ESXi ao seu cluster vSphere, consulte  https://techdocs.broadcom.com/["Documentação técnica Broadcom"].

.Passos
. Na página inicial do vSphere Client, selecione *hosts and clusters*.
. No painel de navegação, selecione o data center que contém o datastore.
. Clique com o botão direito no datastore e selecione *NetApp ONTAP Tools* > *Mount datastore*.
. Na caixa de diálogo *montar datastores em hosts*, selecione os hosts nos quais deseja montar o datastore e, em seguida, selecione *montar*.


O painel de tarefas recentes exibe o progresso.

.Tópico relacionado
link:../manage/add-vsphere-host.html["Adicionar novos hosts VMware vSphere"]
