---
permalink: manage/mount-datastores-on-host.html 
sidebar: sidebar 
keywords: mount NFS VMFS datastore, datastore host access, ONTAP tools datastore mounting, add datastore to ESXi host 
summary: Monte os datastores em hosts adicionais após adicionar hosts ao seu ambiente VMware. 
---
= Montar datastores NFS e VMFS nas ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Montar um datastore fornece acesso ao storage a hosts adicionais depois de adicioná-los ao seu ambiente VMware.


NOTE: Após adicionar o host, aguarde a conclusão da descoberta agendada antes que ele apareça nas ONTAP tools. Como alternativa, você pode executar a descoberta manualmente na tela de visão geral das NetApp ONTAP tools. Para obter informações sobre como adicionar um host ESXi ao seu cluster vSphere, consulte  https://techdocs.broadcom.com/["Documentação técnica Broadcom"].

.Sobre esta tarefa
* Algumas ações com o botão direito do Mouse são desativadas ou indisponíveis dependendo da versão do cliente vSphere e do tipo de datastore selecionado.
+
** Se você estiver usando o vSphere Client 8,0 ou versões posteriores, algumas das opções de clique com o botão direito do Mouse ficam ocultas.
** Da versão vSphere 7.0U3 à vSphere 8.0, embora as opções apareçam, a ação está desativada.


* O vSphere desativa a opção de montagem do armazenamento de dados quando o cluster de hosts está protegido com configurações uniformes.


.Passos
. Na página inicial do vSphere Client, selecione *hosts and clusters*.
. No painel de navegação esquerdo, selecione os data centers que contêm os hosts.
. Para montar datastores NFS/VMFS em um host ou cluster de hosts, clique com o botão direito e selecione *Ferramentas NetApp ONTAP * > *Montar Datastores*.
. Selecione os armazenamentos de dados que você deseja montar e selecione *Mount*.


.O que se segue?
Você pode acompanhar o progresso no painel de tarefas recentes.

.Tópico relacionado
link:../manage/add-vsphere-host.html["Adicionar novos hosts VMware vSphere"]
