---
permalink: manage/remove-storage-from-a-vvols-datastore.html 
sidebar: sidebar 
keywords: shrink vVols datastore, remove storage from vVol datastore, ONTAP tools vVol capacity reduction, virtual volumes datastore resize down 
summary: Exclua um datastore vVols somente quando não restarem vVols no datastore selecionado. 
---
= Reduzir um datastore vVols nas ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Use a ação remover storage do datastore para remover volumes de um vVols datastore nas ONTAP tools, reduzindo sua capacidade quando o storage adicional não for mais necessário.

Utilize a ação "Remover armazenamento do datastore" em qualquer datastore vVols gerenciado pelas ferramentas ONTAP no vCenter Server.

Você não pode remover storage de um volume se ele contiver vVols; a opção de remoção fica desabilitada para esses volumes. Ao remover volumes do datastore, você também tem a opção de excluir os volumes selecionados do storage ONTAP.


NOTE: A operação de redução do armazenamento de dados vVols não é suportada para armazenamentos de dados vVols baseados em sistemas ASA r2.

.Passos
. Na página inicial do vSphere Client, selecione *hosts and clusters*.
. No painel de navegação, selecione o data center que contém o datastore.
. Clique com o botão direito do Mouse no datastore vVol e selecione *NetApp ONTAP Tools* > *Remove storage from datastore*.
. Selecione os volumes que não possuem vVols e selecione *Remover*.
+

NOTE: A opção de selecionar o volume em que vVols residem está desativada.

. Na janela pop-up *Remover armazenamento*, selecione a caixa de seleção *Excluir volumes do cluster ONTAP* para excluir os volumes do datastore e do storage ONTAP e selecione *Excluir*.

