---
permalink: manage/remove-storage-from-a-vvols-datastore.html 
sidebar: sidebar 
keywords: Remove vVol datastore 
summary: A ação Excluir datastore exclui o datastore quando não há vVols no datastore selecionado. 
---
= Diminua o armazenamento de dados do vVols
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esta página explica como remover volumes de um armazenamento de dados vVols .

Utilize a ação "Remover armazenamento do datastore" em qualquer datastore vVols gerenciado pelas ferramentas ONTAP no vCenter Server.

Não é possível remover o armazenamento de um volume se ele contiver vVols; a opção de remoção será desabilitada para esses volumes.  Ao remover volumes do armazenamento de dados, você também tem a opção de excluir os volumes selecionados do armazenamento ONTAP .


NOTE: A operação de redução do armazenamento de dados vVols não é suportada para armazenamentos de dados vVols baseados em sistemas ASA r2.

.Passos
. Na página inicial do vSphere Client, selecione *hosts and clusters*.
. No painel de navegação, selecione o data center que contém o datastore.
. Clique com o botão direito do Mouse no datastore vVol e selecione *NetApp ONTAP Tools* > *Remove storage from datastore*.
. Selecione os volumes que não possuem vVols e selecione *Remover*.
+

NOTE: A opção para selecionar o volume no qual o vVols está residindo está desabilitada.

. Na janela pop-up *Remover armazenamento*, marque *Excluir volumes do cluster ONTAP* para excluir os volumes do armazenamento de dados e do armazenamento ONTAP e selecione *Excluir*.

