---
permalink: manage/reports.html 
sidebar: sidebar 
keywords: ONTAP tools reports, virtual machine reports, datastore reports, VMware storage reporting 
summary: Visualize relatórios de máquinas virtuais e datastores no plug-in ONTAP tools. 
---
= Relatórios do ONTAP tools for VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O plug-in ONTAP tools for VMware vSphere fornece relatórios que ajudam você a monitorar máquinas virtuais e datastores suportados pelo storage ONTAP. Para visualizar esses relatórios, selecione o ícone do plug-in ONTAP tools for VMware vSphere na seção de atalhos do cliente vCenter e, em seguida, selecione a guia Relatórios.

O relatório de Máquinas Virtuais lista as máquinas virtuais detectadas que possuem pelo menos um disco em um datastore baseado em ONTAP, juntamente com métricas de desempenho. Ao expandir o registro da VM, a interface exibe todas as informações do datastore relacionadas ao disco.

O relatório de datastores lista os datastores que ONTAP tools for VMware vSphere descobre e que usam storage ONTAP, juntamente com métricas de desempenho.

Você pode usar a opção Gerenciar colunas para ocultar ou mostrar diferentes colunas.
