---
permalink: manage/reports.html 
sidebar: sidebar 
keywords:  
summary: O plug-in das ferramentas do ONTAP para VMware vSphere fornece relatórios para máquinas virtuais e datastores. 
---
= Relatórios de ferramentas do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O plug-in das ferramentas do ONTAP para VMware vSphere fornece relatórios para máquinas virtuais e datastores. Quando você seleciona o ícone do plug-in das ferramentas do NetApp ONTAP para VMware vSphere na seção Atalhos do cliente vCenter, a interface do usuário navega para a página Visão geral. Selecione a guia relatórios para exibir a máquina virtual e o relatório de datastores.

O relatório de Máquinas virtuais mostra a lista de máquinas virtuais descobertas (devem ter pelo menos um disco de repositórios de dados baseados em armazenamento ONTAP ) com métricas de desempenho. Ao expandir o registro da máquina virtual, a interface exibe todas as informações do armazenamento de dados relacionadas ao disco.

O relatório de datastores lista os datastores descobertos ou reconhecidos ONTAP tools for VMware vSphere que utilizam qualquer armazenamento ONTAP , juntamente com as métricas de desempenho.

Você pode usar a opção Gerenciar colunas para ocultar ou mostrar diferentes colunas.
