---
permalink: manage/reset-manager-password.html 
sidebar: sidebar 
keywords: reset ONTAP tools Manager password, manager admin credential recovery, token-based password reset, appliance administrator reset 
summary: Redefina as credenciais de administrador do ONTAP tools Manager usando um token do console de manutenção. 
---
= Redefinir a senha do Gerenciador de ferramentas do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Caso se esqueça da senha do Gerenciador de ferramentas ONTAP , você pode restaurar o acesso de administrador usando um token de redefinição gerado no console de manutenção das ONTAP tools for VMware vSphere .

.Passos
. Abra um navegador da web e navegue até `https://<ONTAPtoolsIP>:8443/virtualization/ui/` Para acessar o Gerenciador de Ferramentas ONTAP .
. Na página de login, selecione *Redefinir senha*.
. Gere um token de redefinição de senha usando as ONTAP tools for VMware vSphere :
+
.. Faça login no servidor vCenter.
.. Localize a máquina virtual do ONTAP tools e inicie o console da web.
.. Faça login usando as `maint` credenciais.
.. Digitar `2` Para selecionar *Configuração do Sistema*.
.. Digite  `3` para selecionar *Gerar token para redefinir a senha da interface do usuário do manager* e anote o token.


. Na caixa de diálogo de redefinição de senha, insira o token de redefinição, o nome de usuário e a nova senha.
. Selecione *Redefinir* para atualizar as credenciais.
. Faça login no Gerenciador de ferramentas ONTAP com a nova senha.

