---
permalink: manage/reset-manager-password.html 
sidebar: sidebar 
keywords:  
summary: Se você Esqueceu a senha do Gerenciador de ferramentas do ONTAP, poderá redefinir as credenciais do administrador usando o token gerado pelas ferramentas do ONTAP para o console de manutenção do VMware vSphere. 
---
= Redefinir a senha do Gerenciador de ferramentas do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Caso se esqueça da senha do Gerenciador de ferramentas ONTAP , você pode restaurar o acesso de administrador usando um token de redefinição gerado no console de manutenção das ONTAP tools for VMware vSphere .

.Passos
. Abra um navegador da web e navegue até `https://<ONTAPtoolsIP>:8443/virtualization/ui/` Para acessar o Gerenciador de Ferramentas ONTAP .
. Na página de login, selecione *Redefinir senha*.
. Gere um token de redefinição de senha usando as ONTAP tools for VMware vSphere :
+
.. Faça login no servidor vCenter e abra o console de manutenção.
.. Digitar `2` Para selecionar *Configuração do Sistema*.
.. Digitar `3` Selecione *Alterar a senha do usuário 'maint'*.


. Na caixa de diálogo de redefinição de senha, insira o token de redefinição, o nome de usuário e a nova senha.
. Selecione *Redefinir* para atualizar as credenciais.
. Faça login no Gerenciador de ferramentas ONTAP com a nova senha.

