---
permalink: manage/storage-backend.html 
sidebar: sidebar 
keywords: manage storage backends, ONTAP backend systems, storage backend operations, VMware datastore backend configuration 
summary: Gerencie os backends de armazenamento que os hosts ESXi usam para storage. 
---
= Gerencie back-ends de armazenamento nas ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os backends de armazenamento são sistemas que os hosts ESXi usam para storage. Você pode descobrir, modificar e remover backends de armazenamento usando ONTAP tools for VMware vSphere.



[[discover-storage]]
== Descubra o armazenamento

Você pode executar a descoberta do backend de storage sob demanda, em vez de esperar pela próxima descoberta agendada para atualizar os detalhes do storage. Para configurações MetroCluster, execute a descoberta das ONTAP tools manualmente após um switchover.

Siga os passos abaixo para descobrir os backends de armazenamento.

.Passos
. Faça login no cliente vSphere.
. Na página atalhos, selecione *Ferramentas do NetApp ONTAP* na seção plug-ins.
. No painel esquerdo das ferramentas ONTAP , vá para *Backends de armazenamento* e selecione um backend de armazenamento.
. Selecione o menu de reticências verticais e selecione *Discover storage*


Você pode acompanhar o progresso no painel tarefas recentes.



[[modify-storage-backends]]
== Modificar backends de armazenamento

Você pode modificar as credenciais do backend de storage ou o nome da porta. Você também pode modificar o backend de storage para clusters ONTAP globais usando o ONTAP tools Manager. Se o certificado expirar em 30 dias ou menos, o ONTAP tools exibirá um aviso. Modifique o backend de storage e faça upload do novo certificado a partir do administrador do ONTAP.

Quando você modifica o backend de armazenamento, as ONTAP tools for VMware vSphere realizam uma descoberta do backend de armazenamento para atualizar os detalhes do armazenamento.

Siga as etapas nesta seção para modificar um back-end de armazenamento.

. Faça login no cliente vSphere.
. Na página atalhos, selecione *Ferramentas do NetApp ONTAP* na seção plug-ins.
. No painel esquerdo das ferramentas ONTAP , vá para *Backends de armazenamento* e selecione um backend de armazenamento.
. Selecione o menu de reticências verticais e selecione *Modificar* para modificar as credenciais ou o nome da porta. Você pode acompanhar o progresso no painel de tarefas recentes.


Modifique clusters ONTAP globais com o Gerenciador de ferramentas ONTAP da seguinte maneira.

. Inicie o Gerenciador de ferramentas do ONTAP a partir de um navegador da Web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Faça login com as ferramentas do ONTAP para as credenciais de administrador do VMware vSphere fornecidas durante a implantação.
. Selecione backends de armazenamento na barra lateral.
. Selecione o back-end de armazenamento que você deseja modificar.
. Selecione o menu de reticências verticais e selecione *Modificar*.
. Você pode modificar as credenciais ou a porta. Digite *Nome de usuário* e *Senha* para modificar o back-end de armazenamento.




[[remove-storage-backends]]
== Remova as extremidades de armazenamento

Você deve remover todos os armazenamentos de dados anexados ao backend de armazenamento antes de removê-lo.  Siga as etapas abaixo para remover um backend de armazenamento.

. Faça login no cliente vSphere.
. Na página atalhos, selecione *Ferramentas do NetApp ONTAP* na seção plug-ins.
. No painel esquerdo das ferramentas ONTAP , vá para *Backends de armazenamento* e selecione um backend de armazenamento.
. Selecione o menu de reticências verticais e selecione *Remover*. Verifique se o backend de storage não contém nenhum datastore. Você pode acompanhar o progresso no painel de tarefas recentes.


Você pode remover clusters ONTAP globais usando ONTAP tools Manager.

. Inicie o Gerenciador de ferramentas do ONTAP a partir de um navegador da Web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Faça login com as ferramentas do ONTAP para as credenciais de administrador do VMware vSphere fornecidas durante a implantação.
. Selecione *backends de armazenamento* na barra lateral.
. Selecione o back-end de armazenamento que você deseja remover
. Selecione o menu de reticências verticais e selecione *Remover*.




[[drill-down-view-of-storage-backend]]
== Visualização detalhada do back-end de storage

A página de backends de storage lista todos os backends de storage. Você pode descobrir, modificar e remover os backends de storage que adicionou, mas não pode realizar essas operações nas SVMs filhas individuais dentro do cluster.

Selecione o cluster pai ou filho para visualizar o resumo do componente.  Para o cluster pai, use o menu suspenso de ações para descobrir o armazenamento, modificar ou remover o backend de armazenamento.

A página de resumo fornece os seguintes detalhes:

* Status do back-end de storage
* Informações de capacidade
* Informações básicas sobre a VM
* Detalhes do certificado, como o status do certificado e a data de validade.
* Informações de rede, como endereço IP e porta da rede.  Para o SVM filho, as informações são as mesmas do backend de armazenamento pai.
* Privileges permitidos e restritos para o backend de armazenamento. Para o SVM filho, as informações são as mesmas do backend de armazenamento pai. ONTAP tools exibe privilégios apenas em backends de armazenamento baseados em cluster. Se você adicionar SVM como backend de armazenamento, as informações de privilégios não serão exibidas.
* A visualização detalhada do cluster do sistema ASA r2 não inclui a guia de camadas locais quando a propriedade desagregada está definida como "true" para o SVM ou o cluster.
* Para sistemas ASA r2 SVM, o portlet de capacidade não é exibido. O portlet de capacidade é necessário apenas quando a propriedade desagregada está definida como "true" para o SVM ou o cluster.
* Para sistemas ASA R2 SVM, a seção de informações básicas mostra o tipo de plataforma.


A guia interface fornece informações detalhadas sobre a interface.

A guia níveis locais fornece informações detalhadas sobre a lista de agregados.
