---
permalink: manage/unmount-datastores-on-host.html 
sidebar: sidebar 
keywords: unmount NFS VMFS datastore, remove datastore from host, ONTAP tools datastore unmount, ESXi host storage detach 
summary: Desmonte datastores NFS ou VMFS de hosts ESXi usando ONTAP tools. 
---
= Desmontar datastores NFS e VMFS nas ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Use esta tarefa para desmontar um datastore NFS ou VMFS de hosts ESXi. O desmontar de datastore em nível de cluster não é suportado pela interface do usuário ou APIs.

A partir da versão 10.6 do ONTAP tools, desmontar é bloqueado para datastores VMFS protegidos.

.Passos
. Faça login no cliente vSphere.
. Clique com o botão direito do mouse em um objeto de datastore NFS ou VMFS e selecione *Desmontar datastore*.
+
O cliente vSphere abre uma caixa de diálogo e lista os hosts ESXi que montam o datastore. Se o datastore estiver protegido, ONTAP tools bloqueia a solicitação e exibe uma mensagem informando que o datastore está protegido e não pode ser desmontado.

. Selecione um ou mais hosts ESXi para desmontar o datastore.
+
Não é possível desmontar o datastore de todos os hosts. A interface do usuário sugere que você use a operação delete datastore em vez disso.

. Selecione o botão *Desmontar*.
+
A opção *Desmontar armazenamento de dados* está disponível somente quando o host é movido para fora do cluster de hosts protegido.




NOTE: Se um datastore estiver protegido, você deve remover a proteção antes de poder desmontá-lo.

.O que se segue?
Você pode acompanhar o progresso no painel tarefas recentes.
